XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Designates between Local and National</description>
        <label>BU</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary market the vendor operates in</description>
        <label>Local Sales Market</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Markets may be selected</errorMessage>
            <filterItems>
                <field>Market__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The main category that the account operates in</description>
        <label>Primary Category</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active primary Categories may be selected</errorMessage>
            <filterItems>
                <field>Category__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>Indicates the types of services the vendor is paying for</description>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Gen / Data</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a sales rep</errorMessage>
            <filterItems>
                <field>User.Division</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Local_Sales_Market__c</fullName>
        <formula>Account.Local_Sales_Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Local Sales Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <formula>Account.Primary_Category__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Category</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__ZProduct__c.object
<CustomObject>
    <description>The Zuora Product Object.</description>
    <fields>
        <fullName>Ad_Shape__c</fullName>
        <label>Ad Shape</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Square</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown/Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <picklist>
            <picklistValues>
                <fullName>BOWPFV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPWPref</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOW KSB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOF PFV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KNF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KFV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <picklist>
            <picklistValues>
                <fullName>The Knot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The Bump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MinimumSubscriptionTerm__c</fullName>
        <description>This field is used to indicate the product with minimum subscription term, if required.</description>
        <inlineHelpText>This field is used to indicate the product with minimum subscription term, if required.</inlineHelpText>
        <label>Minimum Subscription Term</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge Venue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__SKU__c</fullName>
        <description>The Product SKU.</description>
        <inlineHelpText>The Product SKU.</inlineHelpText>
        <label>SKU</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Zuora Id (external primary key) of this Product.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Zuora Id (external primary key) of this Product.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ZProduct</label>
    <nameField>
        <label>ZProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <picklist>
            <picklistValues>
                <fullName>The Knot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The Bump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concierge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Original Rep</inlineHelpText>
        <label>Modified Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Rep_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__SubscriptionStartDate__c</fullName>
        <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/LocalRenewalBookControllerTest.cls
/*******************************************************************************
 *  Summary         : Test class for LocalRenewalBook Controller
 *  Refer Object    : 
 *  Author          : Tony
 *  RefactorDate    : 12 Dec 2016
 *  Change Log      : refactoring by SF-2.6 release
 ******************************************************************************/
@isTest//(seeAllData = true)
private class LocalRenewalBookControllerTest{
    @isTest static void test_method_one() {
        
        SingleRequestMockTest fakeResponse = new SingleRequestMockTest(200,
                                                 'Complete',
                                                 '{"companyName": "Test Account"}',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        test.startTest();
        Map<String,SObject> sObjectMap  = TestClassUtility.buildLocalData(FALSE);
        test.stopTest();

        Account testAccount = (Account)sObjectMap.get('Account');
        Market__c testMarket = (Market__c)sObjectMap.get('Market__c');
        Category__c testCategory = (Category__c)sObjectMap.get('Category__c');
        zqu__ZProduct__c testZquZProduct = TestClassUtility.createProduct(TRUE);
        Zuora__Subscription__c testZquSubscription = TestClassUtility.createSubscription(TRUE,testAccount);
        
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true limit 2];
        // Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        // Map<String,Schema.RecordTypeInfo> rtOppMapByName = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        // test.startTest();
        // testDataFactoryT tdf = new testDataFactoryT();
        // tdf.CreateLocalTestObjects();
        // test.stopTest();
        // Account testAccount3 = new Account();
        // testAccount3.Name = 'Test Child3 Account ';
        // testAccount3.RecordTypeId = rtMapByName.get('Local').getRecordTypeId();
        // testAccount3.BU__c = 'Local';
        // testAccount3.Website = 'www.google1.com';
        // testAccount3.Type = 'Advertiser';
        // testAccount3.BillingCountry = 'United States';
        // testAccount3.BillingState = 'Alaska';
        // testAccount3.BillingCity = 'US2';
        // testAccount3.BillingStreet = 'US3';
        // testAccount3.BillingPostalCode = tdf.testZip.zipcode__c;
        // testAccount3.parentId = tdf.testAccount.id;
        // testAccount3.Primary_Brand__c = tdf.testBrand.id;
        // testAccount3.Primary_Category__c = tdf.testCategory.id;
        // testAccount3.Local_Sales_Market__c = tdf.testMarket.id;
        // insert testAccount3;
        
        // zqu__ZProduct__c testZquZProduct = new zqu__ZProduct__c();
        // testZquZProduct.Name = 'Test Storefront'; 
        // testZquZProduct.zqu__Category__c = 'Add On Services'; 
        // testZquZProduct.zqu__SKU__c = 'SKU-00000044'; 
        // testZquZProduct.zqu__ZuoraId__c = '2c92c0f84e4d2c02014e655c22cc548c'; 
        // testZquZProduct.LOB__c = 'The Knot'; 
        // testZquZProduct.ProductType__c = 'Internet'; 
        // testZquZProduct.Ad_Shape__c = 'None'; 
        // testZquZProduct.Job_Type__c = 'The Knot'; 
        // testZquZProduct.MinimumSubscriptionTerm__c ='12';
        // insert testZquZProduct;
        
        // Zuora__Subscription__c testZquSubscription = new Zuora__Subscription__c();
        // testZquSubscription.Name = 'Test Subscription';
        // testZquSubscription.Zuora__SubscriptionStartDate__c = Date.Today();
        // testZquSubscription.Zuora__SubscriptionEndDate__c = Date.Today() + 365;
        // testZquSubscription.Zuora__Status__c = 'Active';
        // testZquSubscription.Zuora__Account__c = tdf.testAccount.Id;
        // testZquSubscription.Sales_Rep__c = userList[0].id;
        
        // insert testZquSubscription;
        // testZquSubscription.Zuora__Zuora_Id__c =testZquSubscription.id;
        // update testZquSubscription;
        test.setCurrentPageReference(Page.LocalRenewalBook);
        ApexPages.StandardController sc = new ApexPages.StandardController(testZquSubscription);
        LocalRenewalBookController testcase = new LocalRenewalBookController(sc); 
        string ownerActiveFilter = testcase.ownerActiveFilter;
        
        testcase.filterObject.brandFilter = testAccount.id;
        
        testcase.filterObject.marketFilter.add(new SelectOption('testMarket', string.valueOf(testMarket.Id)));
        
        testcase.filterObject.categoryFilter.add(new SelectOption('testCategory', string.valueOf(testCategory.Id)));
        testcase.filterObject.postalCodeSelected = '12121';
        testcase.filterObject.subscriptionFilter.Sales_Rep__c = userList[0].id;
        testcase.filterObject.subscriptionFilter.Renewal_Rep__c = userList[0].id;
        testcase.filterObject.productLineFilter.Product_Line__c = 'test';
        testcase.filterResults();
        
        testcase.brandFilterFunction();
        testcase.subSelectedMap.put(testZquSubscription.id,false);
        testcase.populateSubscriptions();
        
        testcase.refresh();
        
        testcase.saveRenewalRep();
        testcase.saveFloaterRep();
        
        testcase.salesRepToAssign = userList[1].id;
        testcase.subSelectedMap.clear();
        testcase.saveRenewalRep();
        testcase.saveFloaterRep();
        
        testcase.subSelectedMap.put(testZquSubscription.id,true);
        testcase.saveRenewalRep();
        testcase.saveFloaterRep();
        
        boolean hasNext = testcase.hasNext;
        boolean hasPrevious = testcase.hasPrevious;
        Integer pageNumber = testcase.pageNumber;
        
        testcase.first();
        testcase.last();
        testcase.previous();
        testcase.next();
        
        List<SelectOption> ResultSizeOptions = testcase.getResultSizeOptions();
        List<SelectOption> BrandOptions = testcase.getBrandOptions();
        List<SelectOption> CategoryOptions = testcase.getCategoryOptions();
        List<SelectOption> MarketOptions = testcase.getMarketOptions();
        List<SelectOption> SortByList = testcase.getSortByList();
        List<SelectOption> getUserList = testcase.getUserList();
        List<SelectOption> getUserRenewalList = testcase.getUserRenewalList();
        List<SelectOption> getLocalSalesRepActive = testcase.getLocalSalesRepActive();
        List<SelectOption> getActiveType = testcase.getActiveType();
        List<SelectOption> getLocalAEOnly = testcase.getLocalAEOnly();
        
        testcase.reRenderPanel();
        
    }
}