XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBBS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contract Billing Support Specialist for the customer based on the owning sales representative</description>
        <label>CBSS</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Local_Core_Finance_ARR</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_CBBS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBSS_Email_Is_Matched__c</fullName>
        <description>Indicates whether the CBSS email matches ARR user&apos;s email</description>
        <formula>ISBLANK(CBBS__c)  ||  CBSS_Email__c  =  CBBS__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CBSS Email Is Matched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Account_CBSS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the CBSS associated with the Account should be updated if the account owner is updated.  Created by CSP-596</description>
        <inlineHelpText>If selected, allows for the Account CBSS field to be overridden to a different user than the Account Owner&apos;s CBSS.</inlineHelpText>
        <label>Override Account CBSS</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARR__c</fullName>
        <label>ARR</label>
        <relationshipName>ARR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchUpdateLocalAccountCBSS.cls
global class BatchUpdateLocalAccountCBSS implements Database.Batchable<sObject>, Database.Stateful{
    public Set<Id> updatedCBSSUserIdSet = new Set<Id>();
    public Set<Id> updatedTitleUserIdSet = new Set<Id>();
    public Set<Id> allUserIdSet = new Set<Id>();
    public String query;
    public Id localAccountRecordTypeId;

    global BatchUpdateLocalAccountCBSS(Set<Id> updatedCBSSUserIdSet, Set<Id> updatedTitleUserIdSet) {
        this.updatedCBSSUserIdSet = updatedCBSSUserIdSet;
        this.updatedTitleUserIdSet = updatedTitleUserIdSet;
        this.localAccountRecordTypeId = getLocalAccountRecordTypeId();
        // CSP-2315 Update CBSS Information on Account and Billing Account
        // if updatedCBSSUserIdSet is not isEmpty, means this batch class is called by UserTrigger or Admin run batch one user on demand.
        // if updatedTitleUserIdSet is not isEmpty, means this batch class is called by UserTrigger update user's title.
        this.query = 'SELECT Id, CBBS__c, Owner.ARR__c, CBBS__r.Email, CBBS__r.Phone, Owner.ARR__r.Email, Owner.ARR__r.Phone, Override_Account_CBSS__c, Account.CBSS_Email_Is_Matched__c FROM Account WHERE RecordTypeId = :localAccountRecordTypeId ';
        // Only updated user ARR info, there are not update user's title 
        if(!updatedCBSSUserIdSet.isEmpty() && updatedTitleUserIdSet.isEmpty()) {
            this.query += ' AND (CBBS__c IN :updatedCBSSUserIdSet OR OwnerId IN :updatedCBSSUserIdSet)';
        }
        // Only updated user's title, there are not update user ARR info 
        else if(updatedCBSSUserIdSet.isEmpty() && !updatedTitleUserIdSet.isEmpty()) {
            this.query += ' AND (OwnerId IN :updatedTitleUserIdSet)';
        }
        // Updated user's title and user ARR info
        else if(!updatedCBSSUserIdSet.isEmpty() && !updatedTitleUserIdSet.isEmpty()) {
            allUserIdSet.addAll(updatedCBSSUserIdSet);
            allUserIdSet.addAll(updatedTitleUserIdSet);
            this.query += ' AND (CBBS__c IN :updatedCBSSUserIdSet OR OwnerId IN :allUserIdSet)';
        }
        // when batch is call by Scheduled Jobs
        else {
            this.query += ' AND CBSS_Email_Is_Matched__c = False';
        }
        System.debug('querystring');
        System.debug(this.query);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug(LoggingLevel.INFO, '*** start query: ' + query);
        Database.QueryLocator retVal = Database.getQueryLocator(query);
        return retVal;
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
        System.debug(LoggingLevel.INFO, '***execute scope: ' + scope);
        
        List<Account> listNeedUpdateAccounts = new List<Account>();
        for (Account accRec : scope) {
            // Update CBSS or Last AM Transfer fields on Account.
            accRec = AccountService.assignAccountInfo(accRec, updatedCBSSUserIdSet, updatedTitleUserIdSet); 
            listNeedUpdateAccounts.add(accRec);
        }
        // CSP-2315 Update CBSS Information or Last AM Transfe on Account and Billing Account
        Database.SaveResult[] updateResults = Database.update(listNeedUpdateAccounts, false);
        List<XO_Exception__C> exceptionList = ExceptionUtility.consumeException(updateResults);
        if(!exceptionList.isEmpty()) {
            insert exceptionList;
        } 
    }

    global void finish(Database.BatchableContext BC) {
        // CSP-1659 | run BatchZuoraDataUpdater job if needed
        Set<String> asyncJobInProgressStatusSet = new Set<String>{'Holding', 'Queued', 'Preparing', 'Processing'};
        Integer runningBatchZuoraDataUpdaterJobCount = [SELECT COUNT() FROM AsyncApexJob WHERE ApexClass.Name = 'BatchZuoraDataUpdater' AND Status IN :asyncJobInProgressStatusSet LIMIT 1];
        if (runningBatchZuoraDataUpdaterJobCount == 0 && !Test.isRunningTest()) {
            Database.executebatch(new BatchZuoraDataUpdater());
        }
    }

    private Id getLocalAccountRecordTypeId() {
        Map<Id,Schema.RecordTypeInfo> rtMapById = Schema.SObjectType.Account.getRecordTypeInfosById();
        Id localAccountRecordTypeId;
        for (Schema.RecordTypeInfo rti : rtMapById.values()) {
            if (rti.getName().containsIgnoreCase('Local')) {
                localAccountRecordTypeId = rti.getRecordTypeId();
                break;
            }
        }
        return localAccountRecordTypeId;
    }
}