XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amnesty_Promotion__c</fullName>
        <label>Amnesty Promotion</label>
        <picklist>
            <picklistValues>
                <fullName>100% Amnesty Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50% Amnesty Eligible</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CBBS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contract Billing Support Specialist for the customer based on the owning sales representative</description>
        <label>CBSS</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Local_Core_Finance_ARR</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_CBBS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_on_Payment_Arrangement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate whether a customer is on Payment Arrangement or not.</description>
        <label>Customer on Payment Arrangement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Local_Paid_Status__c</fullName>
        <description>Plan to Deprecated for CSP-2731
            SF-613</description>
        <label>Local Paid Status(deprecated)</label>
        <picklist>
            <picklistValues>
                <fullName>Unpaid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Longest_Past_Due_Date__c</fullName>
        <description>Calculates the amount of days between the past due date and today. Used in email templates including past due balance notifications</description>
        <label>Longest Past Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Override_Account_CBSS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the CBSS associated with the Account should be updated if the account owner is updated.  Created by CSP-596</description>
        <inlineHelpText>If selected, allows for the Account CBSS field to be overridden to a different user than the Account Owner&apos;s CBSS.</inlineHelpText>
        <label>Override Account CBSS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Past_Due_Balance__c</fullName>
        <description>The total of all invoices that are past due</description>
        <label>Past Due Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Invoice_Past_Due_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Create_ARR_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check-box field that controls whether to create a task for ARR when the invoice is past due certain number of days.</description>
        <label>Create ARR Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>For_Non_Amnesty__c</fullName>
        <defaultValue>false</defaultValue>
        <label>For Non Amnesty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Days_Past_Due__c</fullName>
        <label>Number Of Days Past Due</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Send_Email_To_Account_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to determine if an Email should also be sent to the Account Owner when an Account is past due.</description>
        <label>Send Email To Account Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Email_To_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check-box field that controls whether to send email communication to Customer or not when an invoice is past due certain days.</description>
        <label>Send Email To Customer</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Past Due Config</label>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Bill_To_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field will hold the lookup relationship for the Bill To Contact that is being used to sync Bill To information to Zuora.</description>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bill To Billing Accounts</relationshipLabel>
        <relationshipName>Bill_To_Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchAccountPastDueBalanceTest.cls
@isTest
private class BatchAccountPastDueBalanceTest {

    static testMethod void testNormalCreateEmails(){
        
        Invoice_Past_Due_Config__c ipdc = TestClassUtility.createInvoicePastDueConfig(true);
        ipdc.Create_ARR_Task__c = FALSE;
        update ipdc;

        Map<String,SObject> testMap = TestClassUtility.buildLocalData(true);

        Map<Integer, Date> daysLateDateMap = new Map<Integer, Date>();
        
        Integer daysPastDue = (Integer)ipdc.Number_Of_Days_Past_Due__c;
        Date pastDueDate = Date.today().addDays(daysPastDue * -1);
        
        TestClassUtility.DISABLE_TRIGGERS = TRUE;

        List<Folder> folderlist = [SELECT Id FROM Folder WHERE isreadonly = false limit 1];
        Document authDoc = new Document();
        authDoc.Name = 'TheKnot CC ACH Authorization Form';
        authDoc.folderId = folderlist[0].id;
        insert authDoc;

        Account acc = (Account)testMap.get('Account');
        Contact con = (Contact)testMap.get('Contact');
        con.Email = 'testtest@xogrp.com';

        update con;
        Zuora__CustomerAccount__c ca = TestClassUtility.createCustomerAccount(true, acc);
        ca.Bill_To_Contact__c = con.Id;
        update ca;
        
        acc.Past_Due_Balance__c = 100.0;
        acc.Customer_on_Payment_Arrangement__c = false;
        acc.Longest_Past_Due_Date__c = pastDueDate;
        acc.CBBS__c = UserInfo.getUserId();
        acc.Override_Account_CBSS__c = true;
        acc.Local_Paid_Status__c= 'Paid';

        update acc;
        TestClassUtility.DISABLE_TRIGGERS = FALSE;
        
        Test.startTest();
        Database.executeBatch(new BatchAccountPastDueBalanceEmailsAndTasks());
        Test.stopTest();
        System.assert([SELECT Id FROM Task WHERE  subject LIKE 'Account : %'].size()==0);
    
    }

    static testMethod void testAmnestyCreateEmailAndTasks(){

        Invoice_Past_Due_Config__c ipdc = TestClassUtility.createInvoicePastDueConfig(true);
        ipdc.Number_Of_Days_Past_Due__c = 30;
        update ipdc;

        Map<String,SObject> testMap = TestClassUtility.buildLocalData(true);

        Map<Integer, Date> daysLateDateMap = new Map<Integer, Date>();
        
        Integer daysPastDue = (Integer)ipdc.Number_Of_Days_Past_Due__c;
        Date pastDueDate = Date.today().addDays(daysPastDue * -1);
        
        TestClassUtility.DISABLE_TRIGGERS = TRUE;

        List<Folder> folderlist = [SELECT Id FROM Folder WHERE isreadonly = false limit 1];
        Document authDoc = new Document();
        authDoc.Name = 'TheKnot CC ACH Authorization Form';
        authDoc.folderId = folderlist[0].id;
        insert authDoc;

        Account acc = (Account)testMap.get('Account');
        Contact con = (Contact)testMap.get('Contact');
        con.Email = 'testtest@xogrp.com';

        update con;
        Zuora__CustomerAccount__c ca = TestClassUtility.createCustomerAccount(true, acc);
        ca.Bill_To_Contact__c = con.Id;
        update ca;

        acc.Past_Due_Balance__c = 100.0;
        acc.Customer_on_Payment_Arrangement__c = false;
        acc.Longest_Past_Due_Date__c = pastDueDate;
        acc.CBBS__c = UserInfo.getUserId();
        acc.Override_Account_CBSS__c = true;
        acc.Local_Paid_Status__c= 'Paid';
        acc.amnesty_promotion__c = '50% Amnesty Eligible';
        update acc;
        TestClassUtility.DISABLE_TRIGGERS = FALSE;
        
        Test.startTest();
        Database.executeBatch(new BatchAccountPastDueBalanceEmailsAndTasks());
        Test.stopTest();
        System.assert([SELECT Id FROM Task].size()>0);
        
    }


    static testMethod void testCreateAccOwnerEmailAndTasks(){

        Invoice_Past_Due_Config__c ipdc = TestClassUtility.createInvoicePastDueConfig(true);
        ipdc.Send_Email_To_Customer__c = FALSE;
        ipdc.Send_Email_To_Account_Owner__c = true;
        ipdc.Number_Of_Days_Past_Due__c = 70;
        ipdc.For_Non_Amnesty__c = true;
        update ipdc;

        Map<String,SObject> testMap = TestClassUtility.buildLocalData(true);

        Map<Integer, Date> daysLateDateMap = new Map<Integer, Date>();
        
        Integer daysPastDue = (Integer)ipdc.Number_Of_Days_Past_Due__c;
        Date pastDueDate = Date.today().addDays(daysPastDue * -1);
        
        TestClassUtility.DISABLE_TRIGGERS = TRUE;

        List<Folder> folderlist = [SELECT Id FROM Folder WHERE isreadonly = false limit 1];
        Document authDoc = new Document();
        authDoc.Name = 'TheKnot CC ACH Authorization Form';
        authDoc.folderId = folderlist[0].id;
        insert authDoc;

        Account acc = (Account)testMap.get('Account');
        Contact con = (Contact)testMap.get('Contact');
        con.Email = 'testtest@xogrp.com';

        update con;
        Zuora__CustomerAccount__c ca = TestClassUtility.createCustomerAccount(true, acc);
        ca.Bill_To_Contact__c = con.Id;
        update ca;

        acc.Past_Due_Balance__c = 100.0;
        acc.Customer_on_Payment_Arrangement__c = false;
        acc.Longest_Past_Due_Date__c = pastDueDate;
        acc.CBBS__c = UserInfo.getUserId();
        acc.Override_Account_CBSS__c = true;
        acc.Local_Paid_Status__c= 'Paid';
        update acc;
        TestClassUtility.DISABLE_TRIGGERS = FALSE;
        
        Test.startTest();
        Database.executeBatch(new BatchAccountPastDueBalanceEmailsAndTasks());
        Test.stopTest();

        System.assert([SELECT Id FROM Task].size()>0);

    }
}