XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Process_AR_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1511. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - AR&quot; user lookup field and assigns an approval Task to the selected user.</description>
        <inlineHelpText>SF-1511. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - AR&quot; user lookup field and assigns an approval Task to the selected user.</inlineHelpText>
        <label>Approval Process Assignment - AR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Process_Flag_Skip_EchoSign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-1787 | if this box is checked, EchoSign signature will not be required for this Opportunity</description>
        <inlineHelpText>CSP-1787 | if this box is checked, EchoSign signature will not be required for this Opportunity</inlineHelpText>
        <label>Skip EchoSign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Process_Manager_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SF-1506. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - Manager&quot; user lookup field and assigns an approval Task to the selected user.</description>
        <inlineHelpText>SF-1506. When an Approval Process checks this box, the OpportunityTrigger populates the &quot;Approval Process Lookup - Manager&quot; user lookup field and assigns an approval Task to the selected user.</inlineHelpText>
        <label>Approval Process Assignment - Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Expiration_Date__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Local&apos;, Today() + 60, null)</defaultValue>
        <description>Used to determine when the Opportunity will expire and the inventory associated to this Opportunity will be released.</description>
        <label>Opportunity Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reporting_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reporting Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quote_Reporting_Rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRepLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account associated with this Quote.</description>
        <inlineHelpText>The Account associated with this Quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__BillCycleDay__c</fullName>
        <label>Bill Cycle Day</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Service_Activation_Date__c</fullName>
        <inlineHelpText>Service Activation Date should be on or after Start Date and cannot be after Customer Acceptance Date.
If Service Activation Date is not required in Zuora, the Start Date will be used as the Service Activation Date.</inlineHelpText>
        <label>Service Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__Status__c</fullName>
        <description>The Status of the Quote.</description>
        <inlineHelpText>The Status of the Quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Z-Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ValidUntil__c</fullName>
        <description>The Date that the Quote is Valid until.</description>
        <inlineHelpText>The Date that the Quote is Valid until.</inlineHelpText>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>zqu__ZuoraAccountID__c</fullName>
        <label>Zuora Account ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchSendQuotesToZuoraHourlyTest.cls
@isTest
private class BatchSendQuotesToZuoraHourlyTest {

    static testMethod void testSendQuotesToZuoraHourly() {
        
      TestClassUtility.DISABLE_TRIGGERS = TRUE;
      Map<String,SObject> testObjects = TestClassUtility.buildLocalData(true);

      Opportunity testOpp = (Opportunity)testObjects.get('Opportunity');
      testOpp.Name = 'Test Opportunity';
      testOpp.StageName = 'Client Approved';
      testOpp.Type= 'New';
      testOpp.Approval_Process_AR_Assignment__c = false;
      testOpp.Approval_Process_Manager_Assignment__c = false;
      testOpp.Opportunity_Expiration_Date__c = Date.today().addDays(14);
      testOpp.CloseDate = testOpp.Opportunity_Expiration_Date__c;
      testOpp.Approval_Process_Flag_Skip_EchoSign__c = false;
      testOpp.OwnerId = userInfo.getUserId();
      
      update testOpp;

      zqu__Quote__c testQuote = (zqu__Quote__c)testObjects.get('zqu__Quote__c');
      testQuote.Name = 'Test Quote';
      testQuote.zqu__Status__c = 'New';
      testQuote.zqu__Account__c = ((Account)testObjects.get('Account')).Id;
      testQuote.Zqu__ValidUntil__c = Date.Today()-1;
      testQuote.SalesRepLookup__c = userInfo.getUserId();
      testQuote.Reporting_Rep__c = userInfo.getUserId();
      testQuote.zqu__Service_Activation_Date__c = system.today();
      //testQuote.zqu__TermStartDate__c= Date.newinstance(2016, 12, 14);
      testQuote.zqu__BillCycleDay__c='1';
      testQuote.zqu__Opportunity__c = testOpp.Id;
      testQuote.Product_Line__c = 'Internet';
      testQuote.zqu__ZuoraAccountID__c = ((Account)testObjects.get('Account')).Id;

      update testQuote;

      
      TestClassUtility.DISABLE_TRIGGERS = FALSE;

      Task_Creation_Settings__c taskCreateSetting = TestClassUtility.createTaskCreationSettings(true,'Error_sending_a_quote_to_Zuora',true);
      BatchSendQuotesToZuoraHourly bat = new BatchSendQuotesToZuoraHourly();
      bat.quoteOwnerIdMap.put(testQuote.id,testOpp.OwnerId);
      bat.successOppIdSet.add(testOpp.id);
      bat.quoteIdToErrorMessageMap.put(testQuote.id,'test menthod');
      bat.sendQuotesToBilling = false ;


      Test.startTest();
      Database.executeBatch(bat,1);
      Test.stopTest();

      System.assert(!bat.successOppIdSet.isEmpty());

    }

}