XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_AM_Transfer__c</fullName>
        <description>Last date the Account Owner was changed to an Account Manager</description>
        <label>Last AM Transfer</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARR__c</fullName>
        <label>ARR</label>
        <relationshipName>ARR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/AccountServiceTest.cls
@isTest
private class AccountServiceTest {

    static testMethod void testAssignAccountInfo() {
    	Set<Id> updatedCBSSUserIdSet = new Set<Id>();
    	Set<Id> updatedTitleUserIdSet = new Set<Id>();
  		Account accRec = TestClassUtility.createAccount(true);
  		User testUser = [select Id, Name, ARR__r.Email from User 
														where ARR__c != null
														and isActive = true limit 1];

		updatedCBSSUserIdSet.add(testUser.Id);
		updatedTitleUserIdSet.add(testUser.Id);
		accRec.OwnerId = testUser.Id;
		update accRec;

    	Test.startTest();
     	accRec = AccountService.assignAccountInfo(accRec, updatedCBSSUserIdSet, updatedTitleUserIdSet);
     	Test.stopTest();

        System.assert(accRec.Last_AM_Transfer__c == System.today());
    }
}