XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipLabel>Live Subscription Product and Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveEndDate__c</fullName>
        <description>The date when the (segmented) charge ends (or ended).</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__EffectiveStartDate__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <description>The version of the rate plan charge. Each time a charge is amended, Zuora creates a new version of the rate plan charge.</description>
        <label>Version</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/LiveSubscriptionHandlerTest.cls
@isTest
private class LiveSubscriptionHandlerTest {
    static testMethod void testCopySubscription() {
        Account testAccount = TestClassUtility.createAccount(true);
        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__Version__c = 1;
        insert testSubscription;
        Test.startTest();
        Live_Subscription__c testLiveSub = LiveSubscriptionHandler.copySubscription(testSubscription);
        Test.stopTest();

        system.assertEquals(testLiveSub.Name, testSubscription.Name);

    }

    static testMethod void testGenerateLiveSubscriptionPCForNewSub() {
        Account testAccount = TestClassUtility.createAccount(true);
        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__Version__c = 1;
        insert testSubscription;

        Zuora__SubscriptionProductCharge__c testSubscriptionPC1 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC1.Zuora__ChargeNumber__c = 'testSubscriptionPC1';
        testSubscriptionPC1.Zuora__Account__c = testAccount.id;
        Zuora__SubscriptionProductCharge__c testSubscriptionPC2 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC2.Zuora__ChargeNumber__c = 'testSubscriptionPC2';
        testSubscriptionPC2.Zuora__Account__c = testAccount.id;

        List<Zuora__SubscriptionProductCharge__c> listSubProductCharge = new List<Zuora__SubscriptionProductCharge__c>();

        listSubProductCharge.add(testSubscriptionPC1);
        listSubProductCharge.add(testSubscriptionPC2);


        Map<String, Map<String,Zuora__SubscriptionProductCharge__c>> mapSubNameToMapChargeNumberToSubCharge = new Map<String, Map<String,Zuora__SubscriptionProductCharge__c>>();
        mapSubNameToMapChargeNumberToSubCharge.put(testSubscription.Name, new Map<String,Zuora__SubscriptionProductCharge__c>());

        mapSubNameToMapChargeNumberToSubCharge.get(testSubscription.Name).put(testSubscriptionPC1.Zuora__ChargeNumber__c,testSubscriptionPC1);
        mapSubNameToMapChargeNumberToSubCharge.get(testSubscription.Name).put(testSubscriptionPC2.Zuora__ChargeNumber__c,testSubscriptionPC2);

        Map<String,Date> subscriptionNameEffectDateMap = new Map<String,Date>();
        subscriptionNameEffectDateMap.put(testSubscription.Name, Date.today());
        Test.startTest();
        List<Live_Subscription_Product_and_Charge__c> testlistLiveSubPC = LiveSubscriptionHandler.generateLiveSubscriptionPC(mapSubNameToMapChargeNumberToSubCharge,subscriptionNameEffectDateMap);
        Test.stopTest();

        system.assertEquals(2, testlistLiveSubPC.size());

    }

    static testMethod void testGenerateLiveSubscriptionPCForAmendSub() {
        Account testAccount = TestClassUtility.createAccount(true);
        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__Version__c = 1;
        insert testSubscription;

        
        Zuora__SubscriptionProductCharge__c testSubscriptionPC = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC.Zuora__ChargeNumber__c = 'testSubscriptionPC';
        testSubscriptionPC.Zuora__Account__c = testAccount.id;
        Zuora__SubscriptionProductCharge__c testSubscriptionPC1 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC1.Zuora__ChargeNumber__c = 'testSubscriptionPC1';
        testSubscriptionPC1.Zuora__Account__c = testAccount.id;
        Zuora__SubscriptionProductCharge__c testSubscriptionPC2 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC2.Zuora__ChargeNumber__c = 'testSubscriptionPC2';
        testSubscriptionPC2.Zuora__Account__c = testAccount.id;
        List<Zuora__SubscriptionProductCharge__c> listSubProductCharge = new List<Zuora__SubscriptionProductCharge__c>();
        listSubProductCharge.add(testSubscriptionPC);
        listSubProductCharge.add(testSubscriptionPC1);
        listSubProductCharge.add(testSubscriptionPC2);
        insert listSubProductCharge;


        Zuora__SubscriptionProductCharge__c testSubscriptionPC3 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC3.Zuora__ChargeNumber__c = 'testSubscriptionPC3';
        testSubscriptionPC3.Zuora__Account__c = testAccount.id;

        testSubscriptionPC.Zuora__EffectiveEndDate__c = Date.today();

        testSubscriptionPC1.Zuora__EffectiveStartDate__c = Date.today();

        Map<String, Map<String,Zuora__SubscriptionProductCharge__c>> mapSubNameToMapChargeNumberToSubCharge = new Map<String, Map<String,Zuora__SubscriptionProductCharge__c>>();
        mapSubNameToMapChargeNumberToSubCharge.put(testSubscription.Name, new Map<String,Zuora__SubscriptionProductCharge__c>());
        mapSubNameToMapChargeNumberToSubCharge.get(testSubscription.Name).put(testSubscriptionPC.Zuora__ChargeNumber__c,testSubscriptionPC);
        mapSubNameToMapChargeNumberToSubCharge.get(testSubscription.Name).put(testSubscriptionPC1.Zuora__ChargeNumber__c,testSubscriptionPC1);
        mapSubNameToMapChargeNumberToSubCharge.get(testSubscription.Name).put(testSubscriptionPC3.Zuora__ChargeNumber__c,testSubscriptionPC3);

        Map<String,Date> subscriptionNameEffectDateMap = new Map<String,Date>();
        subscriptionNameEffectDateMap.put(testSubscription.Name, Date.today());
        
        Map<String,Date> subscriptionNameEffectDateMap1 = new Map<String,Date>();

        Test.startTest();
        List<Live_Subscription_Product_and_Charge__c> testlistLiveSubPC = LiveSubscriptionHandler.generateLiveSubscriptionPC(mapSubNameToMapChargeNumberToSubCharge,subscriptionNameEffectDateMap);

        Test.stopTest();

        system.assertEquals(4, testlistLiveSubPC.size());


    }

    static testMethod void testGenerateLiveSubscriptionPCForAmendSubFromZuora() {
        Account testAccount = TestClassUtility.createAccount(true);
        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__Version__c = 1;
        insert testSubscription;

        Zuora__SubscriptionProductCharge__c testSubscriptionPC1 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC1.Zuora__ChargeNumber__c = 'testSubscriptionPC1';
        testSubscriptionPC1.Zuora__Account__c = testAccount.id;
        Zuora__SubscriptionProductCharge__c testSubscriptionPC2 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC2.Zuora__ChargeNumber__c = 'testSubscriptionPC2';
        testSubscriptionPC2.Zuora__Account__c = testAccount.id;
        List<Zuora__SubscriptionProductCharge__c> listSubProductCharge = new List<Zuora__SubscriptionProductCharge__c>();
        listSubProductCharge.add(testSubscriptionPC1);
        listSubProductCharge.add(testSubscriptionPC2);

        insert listSubProductCharge;

        Zuora__SubscriptionProductCharge__c testSubscriptionPC3 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC3.Zuora__ChargeNumber__c = 'testSubscriptionPC3';
        testSubscriptionPC3.Zuora__Account__c = testAccount.id;

        testSubscriptionPC1.Zuora__EffectiveStartDate__c = Date.today();

        Map<String, Map<String,Zuora__SubscriptionProductCharge__c>> mapSubNameToMapChargeNumberToSubCharge = new Map<String, Map<String,Zuora__SubscriptionProductCharge__c>>();
        mapSubNameToMapChargeNumberToSubCharge.put(testSubscription.Name, new Map<String,Zuora__SubscriptionProductCharge__c>());

        mapSubNameToMapChargeNumberToSubCharge.get(testSubscription.Name).put(testSubscriptionPC1.Zuora__ChargeNumber__c,testSubscriptionPC1);
        mapSubNameToMapChargeNumberToSubCharge.get(testSubscription.Name).put(testSubscriptionPC3.Zuora__ChargeNumber__c,testSubscriptionPC3);

        Map<String,Date> subscriptionNameEffectDateMap1 = new Map<String,Date>();

        Test.startTest();
        List<Live_Subscription_Product_and_Charge__c> testlistLiveSubPC1 = LiveSubscriptionHandler.generateLiveSubscriptionPC(mapSubNameToMapChargeNumberToSubCharge,subscriptionNameEffectDateMap1);
        Test.stopTest();

        system.assertEquals(3, testlistLiveSubPC1.size());
    }
}