XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Hold_Expiry_Date__c</fullName>
        <inlineHelpText>The date that this inventory slot is reserved through.  If a spot has a hold expiry date of 2/1/2017, for example, it becomes available as soon as the date switches to 2/2/2017</inlineHelpText>
        <label>Held Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Waitlist_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Waitlist Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Available for Purchase</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>INVN-{000000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipLabel>Live Subscription Product and Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a ZProduct.</description>
    <label>Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/EmailUtilityTest.cls
@isTest
private class EmailUtilityTest {
	@testSetup static void testSetupData(){
		TestClassUtility.generateQuotePdfConfig(true);
	}

    static testMethod void testCreateTwoDayContractEmail() {
        Opportunity testOpp = TestClassUtility.createOpportunity(true);

        Test.startTest();
		Messaging.SingleEmailMessage emailResponse = EmailUtility.createTwoDayContractEmail(testOpp);
		Test.stopTest();

        System.assert(emailResponse != null);
    }

    static testMethod void testCreateExpiredContractEmail() {
        Opportunity testOpp = TestClassUtility.createOpportunity(true);

        Test.startTest();
        Messaging.SingleEmailMessage emailResponse = EmailUtility.createExpiredContractEmail(testOpp);
        Test.stopTest();

        System.assert(emailResponse != null);
    }

    static testMethod void testCreateWaitListOnDeckEmail() {
		Product2 testProduct = TestClassUtility.createLocalProduct2(true);
    	zqu__ProductRatePlan__c testProductRatePlan = TestClassUtility.createProductRatePlan(true, testProduct);

    	Inventory__c testInventory = TestClassUtility.createInventory(false,testProductRatePlan);
    	testInventory.Inventory_Hold_Expiry_Date__c = Date.today();
    	testInventory.Waitlist_Account__c = TestClassUtility.createAccount(true).Id;
    	Database.insert(testInventory,false);

		Test.startTest();
        Messaging.SingleEmailMessage emailResponse = EmailUtility.createWaitListOnDeckEmail(testInventory);
        Test.stopTest();

        System.assert(emailResponse != null);
    }

    static testMethod void testCreateEmailBody() {
		String title = 'testTitle';
		String bodyText = 'testBodyText';

		Test.startTest();
        String responseString = EmailUtility.createEmailBody(title,bodyText);
        Test.stopTest();

        System.assert(String.isNotBlank(responseString));
    }

    static testMethod void testGenerateEmail() {    
    	Id templateId = [SELECT Id FROM EmailTemplate WHERE isActive = true Limit 1].Id;
    	Id whatId = TestClassUtility.createAccount(true).Id;
    	Id targetObjectId = TestClassUtility.createContact(true).Id;
    	Id orgWideEmailAddressId = [SELECT Id FROM OrgWideEmailAddress LIMIT 1].Id;
    	String replyToAddress = 'test@test.com'; 
    	String senderDisplayName = 'Test Name';

        Test.startTest();
       	Messaging.SingleEmailMessage newEmail = EmailUtility.generateEmail(templateId, whatId, targetObjectId, false, orgWideEmailAddressId, replyToAddress, senderDisplayName);
        Test.stopTest();

        System.assert(newEmail != null);
    }

    static testMethod void testCreateLiveChargeEmail() {    
        String userId = String.valueOf(UserInfo.getUserId());
        String subZuoraId = 'testsubscriptionZUoraId';

        Account testAccount = TestClassUtility.createAccount(true);
        Live_Subscription__c testLiveSubs = TestClassUtility.createLiveSub(true,testAccount);
        Live_Subscription_Product_and_Charge__c testLSPC = TestClassUtility.createliveCharge(true,testAccount,testLiveSubs);


        List<Live_Subscription_Product_and_Charge__c> listLSPC = new List<Live_Subscription_Product_and_Charge__c>();
        listLSPC.add(testLSPC);

        Map<String,list<Live_Subscription_Product_and_Charge__c>> mapSubZuoraIdLiveCharges = new Map<String,list<Live_Subscription_Product_and_Charge__c>>();
        mapSubZuoraIdLiveCharges.put(subZuoraId,listLSPC);

        Test.startTest();
        List<Messaging.SingleEmailMessage> listNewEmail = EmailUtility.createLiveChargeEmail(userId, mapSubZuoraIdLiveCharges);
        Test.stopTest();

        System.assertEquals(1, listNewEmail.size());
    }

    static testMethod void testSendSalesRepRSDEmail() {    
        String userFullName = String.valueOf(UserInfo.getUserId());

        Account testAccount = TestClassUtility.createAccount(true);
        Set<Id> setAccId = new Set<Id>();
        setAccId.add(testAccount.Id);

        Test.startTest();
        List<XO_Exception__c> xoExceptionList = EmailUtility.sendSalesRepRSDEmail(setAccId, userFullName);
        Test.stopTest();

        System.assertEquals(0, xoExceptionList.size());
    }
}