XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBBS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contract Billing Support Specialist for the customer based on the owning sales representative</description>
        <label>CBSS</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Local_Core_Finance_ARR</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_CBBS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBSS_Email__c</fullName>
        <description>The email address that is listed on the user account for the CBSS user</description>
        <label>CBSS Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_AM_Transfer__c</fullName>
        <description>Last date the Account Owner was changed to an Account Manager</description>
        <label>Last AM Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Override_Account_CBSS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the CBSS associated with the Account should be updated if the account owner is updated.  Created by CSP-596</description>
        <inlineHelpText>If selected, allows for the Account CBSS field to be overridden to a different user than the Account Owner&apos;s CBSS.</inlineHelpText>
        <label>Override Account CBSS</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARR__c</fullName>
        <label>ARR</label>
        <relationshipName>ARR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchUpdateLocalAccountCBSSTest.cls
/*******************************************************************************
 *  Summary      : Test class for BatchCloseExpiredLocalOppsSchedJob
 *  Refer Object : 
 *  Author       : Tony
 *  RefactorDate : 19 Dec 2016
 *  Change Log   : Refactoring by CSP-1686
 ******************************************************************************/
@isTest
private class BatchUpdateLocalAccountCBSSTest {
    static testMethod void testUpdateARR() {
        
        //Map<String, SObject> testObjects = TestClassUtility.buildZQUTestObjects(false);
        Map<String, SObject> testObjects = TestClassUtility.buildLocalData(FALSE);
        Set<Id> updatedCBSSUserIdSet = new Set<Id>();
        Set<Id> updatedTitleUserIdSet = new Set<Id>();
        List<User> userList = [select Id, Name, ARR__c from User where Id != :UserInfo.getUserId() and isActive = true and ARR__c != null limit 2];
        for (User userRecord : userList) {
            updatedCBSSUserIdSet.add(userRecord.Id);
        }
        Account testAccount = (Account)testObjects.get('Account');
        testAccount.Override_Account_CBSS__c = True;
        testAccount.CBBS__c =userList[0].id;
        update testAccount;
        
        Test.startTest();
        BatchUpdateLocalAccountCBSS bb = new BatchUpdateLocalAccountCBSS(updatedCBSSUserIdSet,updatedTitleUserIdSet);
        Database.executeBatch(bb);
        Test.stopTest();

        Account assertAccount = [select Id, CBSS_Email__c, CBBS__r.Email From Account where id =: testAccount.Id];
        System.assert(assertAccount.CBSS_Email__c == assertAccount.CBBS__r.Email);
    }
    static testMethod void testUpdateUserTitle() {
        
        Map<String, SObject> testObjects = TestClassUtility.buildLocalData(FALSE);
        Set<Id> updatedCBSSUserIdSet = new Set<Id>();
        Set<Id> updatedTitleUserIdSet = new Set<Id>();
        List<User> userList = [select Id, Name from User where Id != :UserInfo.getUserId() and isActive = true and Title = 'Account Manager' limit 2];
        for (User userRecord : userList) {
            updatedTitleUserIdSet.add(userRecord.Id);
        }
        Account testAccount = (Account)testObjects.get('Account');
        testAccount.OwnerId = userList[0].id;
        update testAccount;
        
        Test.startTest();
        BatchUpdateLocalAccountCBSS bb = new BatchUpdateLocalAccountCBSS(updatedCBSSUserIdSet,updatedTitleUserIdSet);
        Database.executeBatch(bb);
        Test.stopTest();

        Account assertAccount = [select Id, CBSS_Email__c, Last_AM_Transfer__c From Account where id =: testAccount.Id];
        System.assert(assertAccount.Last_AM_Transfer__c == System.today());
    }
    static testMethod void testUpdateUserTitleAndARR() {
        
        Map<String, SObject> testObjects = TestClassUtility.buildLocalData(FALSE);
        Set<Id> updatedCBSSUserIdSet = new Set<Id>();
        Set<Id> updatedTitleUserIdSet = new Set<Id>();
        List<User> userList = [select Id, Name, ARR__r.Email from User where Id != :UserInfo.getUserId() and isActive = true and Title = 'Account Manager' limit 2];
        for (User userRecord : userList) {
            updatedTitleUserIdSet.add(userRecord.Id);
            updatedCBSSUserIdSet.add(userRecord.Id);
        }
        Account testAccount = (Account)testObjects.get('Account');
        testAccount.OwnerId = userList[0].id;
        testAccount.Override_Account_CBSS__c = FALSE;
        update testAccount;
        
        Test.startTest();
        BatchUpdateLocalAccountCBSS bb = new BatchUpdateLocalAccountCBSS(updatedCBSSUserIdSet,updatedTitleUserIdSet);
        Database.executeBatch(bb);
        Test.stopTest();

        Account assertAccount = [select Id, CBSS_Email__c, CBBS__r.Email, Last_AM_Transfer__c From Account where id =: testAccount.Id];
        System.assert(assertAccount.Last_AM_Transfer__c == System.today());

    }
}