XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cancel_Reason_Notes__c</fullName>
        <label>Cancel Reason Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Adjusted Cancel Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blank Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Bad Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Externally Resolved (Until bonus has fully changed over)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Reporter Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efforts Exhausted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good Faith Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructions/Policy Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max attempts no contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max Attempts - No Written Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promised Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refusal to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested Contract Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested to Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Remains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved Hard Concessions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved No Concessions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Saved_By__c</fullName>
        <label>Saved By</label>
        <picklist>
            <controllingField>Outcome__c</controllingField>
            <picklistValues>
                <fullName>Dashboard / Stats Walkthrough</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dedicated Point of Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downsell/Remove Upgrades</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explanation of Stats/Clickthroughs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offering Non-Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storefront Redesign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Market/Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Freeze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset Expectations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dashboard Walkthrough</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Make Good</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Name__c</fullName>
        <description>Lists the zuora subscription number (e.g. A-S00142538)</description>
        <externalId>true</externalId>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Feature_Requested_Cancelled__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested Cancelled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Name__c</fullName>
        <label>Subscription Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Product_Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Feature Requested Cancelled</relationshipLabel>
        <relationshipName>Feature_Requested_Cancelled</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feature Requested Cancelled</label>
    <nameField>
        <displayFormat>FRC-{00000}</displayFormat>
        <label>Feature Requested Cancelled Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Requested Cancelled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Process_Flag_Skip_EchoSign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSP-1787 | if this box is checked, EchoSign signature will not be required for this Opportunity</description>
        <inlineHelpText>CSP-1787 | if this box is checked, EchoSign signature will not be required for this Opportunity</inlineHelpText>
        <label>Skip EchoSign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancel_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact who signs the contract in EchoSign.</inlineHelpText>
        <label>Contract Signer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Expiration_Date__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Local&apos;, Today() + 60, null)</defaultValue>
        <description>Used to determine when the Opportunity will expire and the inventory associated to this Opportunity will be released.</description>
        <label>Opportunity Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Saved_By_Notes__c</fullName>
        <description>Store cancel case notes info</description>
        <label>Saved By Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Saved_By_Reason__c</fullName>
        <description>Store cancel case reason info</description>
        <label>Saved By Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skip_EchoSign_Reason_Code__c</fullName>
        <description>CSP-1818</description>
        <label>Skip EchoSign Reason Code</label>
        <picklist>
            <picklistValues>
                <fullName>Auto Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Make Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manually Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provided IO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R/N Signature on File</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Zuora__SubscriptionChargeNumber__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Charge Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/CancelCaseController.cls
/**
 * The controller for the cancel case lightning components.
 */
public with sharing class CancelCaseController {
  public static final String CANCEL = 'Cancel';
  public static final String DOWNGRADE = 'Downgrade';
  public static final String PROSPECTING = 'PROSPECTING';
  public static final String SAVED = 'saved';

  /**
   * Get all picklist values.
   *
   * @return Map<String, List<PicklistValueWrapper>>.
   */
  @AuraEnabled
  public static Map<String, List<PicklistValueWrapper>> getAllPicklistOptions() {

    List<PicklistValueWrapper> originOptions = convertMapToWrapper(DataUtility.buildPicklistEntryMap('Case','Origin'));
    List<PicklistValueWrapper> typeOptions = convertMapToWrapper(DataUtility.buildPicklistEntryMap('Case','Type'));
    List<PicklistValueWrapper> reasonOptions = convertMapToWrapper(DataUtility.buildPicklistEntryMap('Case','Reason'));
    List<PicklistValueWrapper> outcomeOptions = convertMapToWrapper(DataUtility.buildPicklistEntryMap('Case','Outcome__c'));
    List<PicklistValueWrapper> savedByOptions = convertMapToWrapper(DataUtility.buildPicklistEntryMap('Case','Saved_By__c'));

    return new Map<String, List<PicklistValueWrapper>> {
        'originOptions' => originOptions,
        'typeOptions' => typeOptions,
        'reasonOptions' => reasonOptions,
        'outcomeOptions' => outcomeOptions,
        'savedByOptions' => savedByOptions
    };
  }

  /**
   * Get or create a case for the account id.
   *
   * @param accountId - The account id.
   * @return Case object.
   */
  @AuraEnabled
  public static CaseService.CaseInfoWrapper getCaseForAccount(String accountId) {
    try {
      return CaseService.getInstance().getOrCreateCaseForAccount(accountId);
    } 
    catch (Exception e) {
      throw LightningUtility.createException(e.getMessage());
    }
  }

  /**
   * Get or create a case for the account id.
   *
   * @param Map<String, Object> caseValues The case values to upsert.
   * @param Boolean insertOpportunity If true create a cancel case Opportunity.
   * @return Case object.
   */
  @AuraEnabled
  public static Map<String, String> saveCase(String caseValuesStr, Boolean insertOpportunity, 
                              Integer currentPage, Boolean isCloseCase, Boolean isAssignOwner, Boolean isSaveLater) {
    String OpportunityId = '';
    Map<String, Object> caseValues = ((Map<String, Object>)JSON.deserializeUntyped(caseValuesStr));

    try {
 
      Case caseInfo = CaseService.getInstance().getCaseInfo(caseValues, currentPage, isCloseCase, isAssignOwner, isSaveLater);
      Case upsertedCase = CaseService.getInstance().upsertCase(caseInfo);

      if (caseValues.get('associatedTaskOrEmail') != null) {
        String taskId = String.valueOf(caseValues.get('associatedTaskOrEmail'));

        CaseService.addCaseToTask(upsertedCase.Id, taskId);
      }

      if(insertOpportunity && caseValues.get('outcome') == 'Cancelled') {
        OpportunityId = generateCancelOpp(upsertedCase.Id);
      }
      return new Map<String, String> {
          'OpportunityId' => OpportunityId
      };
    } 
    catch (Exception e) {
      throw LightningUtility.createException(e.getMessage());
    }
  }

  /**
   * Upload file as attachment
   *
   * @param String parentId The parent the attachment belongs to.
   * @param String fileName The name of the file.
   * @param String base64Data The file contents.
   * @param String contentType The file type.
   * @param String fileId The attachment id.
   * @return String Id of the attachment.
   */
  @AuraEnabled
  public static String saveFileChunk(String parentId, String fileName, String base64Data, String contentType, String attachmentId) {
    try {
      if (String.isBlank(attachmentId)) {
          attachmentId = CaseService.getInstance().saveFile(parentId, fileName, base64Data, contentType);
      } 
      else {
        CaseService.getInstance().appendToFile(attachmentId, base64Data);
      }
      return attachmentId;
    } 
    catch (Exception e) {
      throw LightningUtility.createException(e.getMessage());
    }
  }

  /**
   * Delete an attachment
   *
   * @param String attachmentId The attachment id.
   * @return Map<String, Boolean>.
   */
  @AuraEnabled
  public static Map<String, Boolean> removeAttachment(String attachmentId) {
    try {
      Boolean result = CaseService.getInstance().deleteAttachment(attachmentId);
      return new Map<String, Boolean>{
          SAVED => result
      };
    } 
    catch (Exception e) {
      throw LightningUtility.createException(e.getMessage());
    }
  }

  /**
   * Create the cancel opportunity for the cancel case.
   *
   * @param cancelCaseId The case Id.
   */
  public static String generateCancelOpp(Id cancelCaseId) {

    //TODO: CaseService
    Case CancelCase = [SELECT Id, CaseNumber, OwnerId, AccountId, Cancel_Reason_Notes__c, Reason FROM Case WHERE Id = :cancelCaseId];

    list<Feature_Requested_Cancelled__c> listFRCs = [SELECT Id, Subscription_Name__c, Subscription_Product_Charge__r.Zuora__SubscriptionChargeNumber__c 
                        FROM Feature_Requested_Cancelled__c WHERE Case__c =:cancelCaseId AND Status__c = 'Cancelled'];

    RecordType localOpportunityRecordType = [SELECT Id, Name FROM RecordType 
                                            WHERE SobjectType = 'Opportunity' 
                                            AND RecordType.Name = 'Local' LIMIT 1];

    Opportunity newOpp = new Opportunity();

    if (localOpportunityRecordType != null) {
      newOpp.RecordTypeId = localOpportunityRecordType.Id;
    }
    newOpp.OwnerId = Label.Cancel_Opportunity_Owner_Id;  
    newOpp.Name = String.format('Cancel Case {0} Cancel Request', new String[] {cancelCase.CaseNumber});
    if(!Test.isRunningTest()) {
      newOpp.Contract_Signer__c = Label.Contact_Signer_for_Cancel_Opp;
    }
    newOpp.AccountId = cancelCase.AccountId;
    newOpp.CloseDate = Date.today().addDays(7);
    newOpp.Opportunity_Expiration_Date__c = Date.today().addDays(7);
    newOpp.StageName = PROSPECTING;
    newOpp.Type = CANCEL;
    newOpp.Approval_Process_Flag_Skip_EchoSign__c = true;
    newOpp.Skip_EchoSign_Reason_Code__c = DOWNGRADE;
    newOpp.Cancel_Case__c = cancelCase.Id;
    newOpp.Saved_By_Notes__c = cancelCase.Cancel_Reason_Notes__c;
    newOpp.Saved_By_Reason__c = cancelCase.Reason;
    if(!listFRCs.isEmpty()) {
      newOpp.Description = 'The following Subscription Product Charge is being cancelled: ';
      for(Feature_Requested_Cancelled__c FRC : listFRCs) {
        newOpp.Description += '\n Subscription Name: '+FRC.Subscription_Name__c +' with Charge Number: '+ FRC.Subscription_Product_Charge__r.Zuora__SubscriptionChargeNumber__c ;
      }
    }
    insert newOpp;
    return newOpp.Id;
  }
  /**
   * This method used to convert format to PicklistValueWrapper from Map 
   * 
   *   @author Mason
   *   @param mapPicklistValue .
   *   @date   2018-10-29
   */

  @AuraEnabled
  public static list<PicklistValueWrapper> convertMapToWrapper(Map<String,String> mapPicklistValue) {

    list<PicklistValueWrapper> listPicklistObj = new list<PicklistValueWrapper>{
      new PicklistValueWrapper('', '')
    };

    for(String label : mapPicklistValue.keySet()){
      listPicklistObj.add(new PicklistValueWrapper(label,mapPicklistValue.get(label)));
    }
    return listPicklistObj;
  }

  /**
   * This class used to return picklist value object 
   * 
   *   @author Mason
   *   @date   2018-10-29
   */
  public with sharing class PicklistValueWrapper {
    @AuraEnabled
    public String label { get; set; }
    @AuraEnabled
    public String value { get; set; }
    public PicklistValueWrapper(String label, String value) {
      this.label = label;
      this.value = value;
    }
  }

}