XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CBBS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contract Billing Support Specialist for the customer based on the owning sales representative</description>
        <label>CBSS</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Local_Core_Finance_ARR</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_CBBS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBSS_Email_Is_Matched__c</fullName>
        <description>Indicates whether the CBSS email matches ARR user&apos;s email</description>
        <formula>ISBLANK(CBBS__c)  ||  CBSS_Email__c  =  CBBS__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CBSS Email Is Matched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CBSS_Email__c</fullName>
        <description>The email address that is listed on the user account for the CBSS user</description>
        <label>CBSS Email</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CBSS_Phone__c</fullName>
        <description>The phone number that is listed on the user account for the CBSS user</description>
        <label>CBSS Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_AM_Transfer__c</fullName>
        <description>Last date the Account Owner was changed to an Account Manager</description>
        <label>Last AM Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Override_Account_CBSS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the CBSS associated with the Account should be updated if the account owner is updated.  Created by CSP-596</description>
        <inlineHelpText>If selected, allows for the Account CBSS field to be overridden to a different user than the Account Owner&apos;s CBSS.</inlineHelpText>
        <label>Override Account CBSS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ARR__c</fullName>
        <label>ARR</label>
        <relationshipName>ARR</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/AccountService.cls
public without sharing class AccountService {

    /**
    * @purpose For BatchUpdateLocalAccountCBSS class assign cbbs info or Last AM Transfer info on Account
    * @author  Mason
    * @date    2019-1-10
    * @param   Account accRec    need update account record
    * @param   Set<Id> updatedCBSSUserIdSet   User's ids when updated user's ARR info
    * @param   Set<Id> updatedTitleUserIdSet  User's ids when updated user's title info
    * @return  Account accRec                 have updaed account recrod
    */
    public static Account assignAccountInfo(Account accRec, Set<Id> updatedCBSSUserIdSet, Set<Id> updatedTitleUserIdSet) {
        // CSP-2315 Update CBSS Information on Account and Billing Account
        if(updatedCBSSUserIdSet.contains(accRec.OwnerId) || !accRec.CBSS_Email_Is_Matched__c || updatedCBSSUserIdSet.contains(accRec.CBBS__c)){
           if(!accRec.Override_Account_CBSS__c){
                accRec.CBBS__c = accRec.Owner.ARR__c;
                accRec.CBSS_Email__c = accRec.Owner.ARR__r.Email;
                accRec.CBSS_Phone__c = accRec.Owner.ARR__r.Phone;
            }else{
                accRec.CBSS_Email__c = accRec.CBBS__r.Email;
                accRec.CBSS_Phone__c = accRec.CBBS__r.Phone;
            } 
        }
        // Update Last AM Transfer on Account where user title change to Account Manager
        if(updatedTitleUserIdSet.contains(accRec.OwnerId)) {
            accRec.Last_AM_Transfer__c = System.today();
        }
        return accRec;
    }
}