XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Pre_Zuora_TermEndDate__c</fullName>
        <label>Pre Zuora Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscription_Version__c</fullName>
        <label>Subscription Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/LiveSubscriptionTriggerTest.cls
@isTest
private class LiveSubscriptionTriggerTest {
    @testSetup static void buildTestData() {
        Account testAccount = TestClassUtility.createAccount(true);
        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__Version__c = 1;
        insert testSubscription;
    }

    static testMethod void testLiveSUbscriptionUpdate() {
        

        Live_Subscription__c newLiveSubscription  = [select Id,Subscription_Version__c from Live_Subscription__c limit 1];
        newLiveSubscription.Subscription_Version__c = 2;

        Test.startTest();
        update newLiveSubscription;
        Test.stopTest();

        Live_Subscription__c liveSubscriptionAfterUpdate = [Select id,Pre_Zuora_TermEndDate__c from Live_Subscription__c where id =: newLiveSubscription.Id];
        system.assertNotEquals(liveSubscriptionAfterUpdate.Pre_Zuora_TermEndDate__c, null);
    }

    static testMethod void testLiveSUbscriptionDelete() {

        Live_Subscription__c newLiveSubscription  = [select Id from Live_Subscription__c limit 1];

        Test.startTest();
        delete newLiveSubscription;
        Test.stopTest();

        List<Live_Subscription__c> listliveSubscriptionAfterDelete = [Select id,Pre_Zuora_TermEndDate__c from Live_Subscription__c];
        system.assertEquals(0, listliveSubscriptionAfterDelete.size());
    }
}