XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account_Snapshots__c.object
<CustomObject>
    <description>CSP-3326 30/60/90 Day on Cancel Saves</description>
    <fields>
        <fullName>Account_Value__c</fullName>
        <description>SUM(Zuora_MonthlyRecurringRevenue_c) for related Account when Commission_Line_Item_Status_c = Live</description>
        <label>Account Value</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Account Snapshots</relationshipLabel>
        <relationshipName>Account_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Snapshot_Period__c</fullName>
        <label>Snapshot Period</label>
        <picklist>
            <picklistValues>
                <fullName>0 Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 Day</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Snapshots</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Account Snapshots Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchCalculateAccountValue.cls
global class BatchCalculateAccountValue implements Schedulable, Database.Batchable<sObject> {
    public String query;
    private static final String ACCSNAP_QUERY = ' SELECT Id, Case__c, Case__r.AccountId, Snapshot_Date__c, Snapshot_Period__c ' +
                                                ' FROM Account_Snapshots__c WHERE Snapshot_Date__c = TODAY ';




    global void execute(SchedulableContext sc) {
        Database.executeBatch(this);
    }

    global BatchCalculateAccountValue() {
        this.query = ACCSNAP_QUERY;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    /**
     * @purpose Calculate Account value for Account Snapshots
     * @author  Mason
     * @date    2018-10-09
     * @param   List<Account_Snapshots__c>  the local Account_Snapshots__c under the case
     */
    global void execute(Database.BatchableContext BC, list<Account_Snapshots__c> scope) {
        Map<Id, Decimal> mapAccIdValue = new Map<Id, Decimal>();
        Set<Id> setAccId = new Set<Id>();
        
        for(Account_Snapshots__c currentAccSnap : scope) {
            Id accId = currentAccSnap.Case__r.AccountId;
            if(String.isNotBlank(accId)) {
                setAccId.add(accId);
            }
        }
        //Get Acccount And sum effective Revenue Mapping
        mapAccIdValue = CaseService.composeAccAndRevenueMapping(setAccId);
        
        //Fill account value under Account Snapshots
        for(Account_Snapshots__c currentAccSnap : scope) {
            Id accId = currentAccSnap.Case__r.AccountId;

            if(mapAccIdValue.containsKey(accId)) {
                currentAccSnap.Account_Value__c = mapAccIdValue.get(accId);
            }
            else{
                currentAccSnap.Account_Value__c = 0;
            }
        }

        //Update account Snapshots and insert xo exception if there is
        Database.SaveResult[] updateResults = Database.update(scope, false);
        List<XO_Exception__C> listException = ExceptionUtility.consumeException(updateResults);
        if(!listException.isEmpty()){
            insert listException;
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}