XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Live_at_Month_Start__c</fullName>
        <description>Total Value of &quot;Live&quot; items as of the first of the current month</description>
        <label>Live $ at Month Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>TestData</fullName>
        <active>true</active>
        <label>TestData</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Original_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>OrignialSubscription1</relationshipLabel>
        <relationshipName>OrignialSubscription1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipLabel>Live Subscription Product and Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchCalcLiveChargeTCVMonthlyTest.cls
@isTest
private class BatchCalcLiveChargeTCVMonthlyTest {

    static testMethod void testCalcLiveChargeTCV() {
        
        List<User> usrlist = [SELECT Id, title FROM User WHERE isActive = TRUE AND title = 'Account Manager' limit 1];
        
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Account testAccount = (Account)testData.get('Account');
        testAccount.ownerid = usrlist[0].id;
        update testAccount;

        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__TermStartDate__c = Date.today();
        insert testSubscription;

        List<Live_Subscription__c> liveSubList = [SELECT Id FROM Live_Subscription__c WHERE Original_Subscription__c =: testSubscription.id];

        Live_Subscription_Product_and_Charge__c lspc1 = TestClassUtility.createLiveSubscriptionPC(TRUE,testAccount, liveSubList[0]);
        
        Live_Subscription_Product_and_Charge__c lspc2 = TestClassUtility.createLiveSubscriptionPC(TRUE,testAccount, liveSubList[0]);
        
        TestClassUtility.DISABLE_TRIGGERS = FALSE;
        

        Test.startTest();
        System.schedule('BatchCalcLiveChargeTCVMonthly', '0 50 7 ? * *', new BatchCalcLiveChargeTCVMonthly());
        Database.executeBatch(new BatchCalcLiveChargeTCVMonthly());
        Test.stopTest();
        
        Account finalAccount = [SELECT Id, Live_at_Month_Start__c FROM Account WHERE Id =: testAccount.Id];

        System.assertEquals(40,finalAccount.Live_at_Month_Start__c);
    }

    static testMethod void testCalcNoneLiveChargeTCV() {
        
        List<User> usrlist = [SELECT Id, title FROM User WHERE isActive = TRUE AND title = 'Account Manager' limit 1];
        
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Account testAccount = (Account)testData.get('Account');
        testAccount.ownerid = usrlist[0].id;
        update testAccount;

        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__TermStartDate__c = Date.today().adddays(366);
        insert testSubscription;

        List<Live_Subscription__c> liveSubList = [SELECT Id FROM Live_Subscription__c WHERE Original_Subscription__c =: testSubscription.id];

        Live_Subscription_Product_and_Charge__c lspc1 = TestClassUtility.createLiveSubscriptionPC(TRUE,testAccount, liveSubList[0]);
        
        TestClassUtility.DISABLE_TRIGGERS = FALSE;
        

        Test.startTest();
        Database.executeBatch(new BatchCalcLiveChargeTCVMonthly());
        Test.stopTest();
        
        Account finalAccount = [SELECT Id, Live_at_Month_Start__c FROM Account WHERE Id =: testAccount.Id];

        System.assertEquals(0,finalAccount.Live_at_Month_Start__c);
    }

}