XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>TestData</fullName>
        <active>true</active>
        <label>TestData</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Original_Sales_Rep__c.object
<CustomObject>
    <description>CSP-3120</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Original Sales Reps</relationshipLabel>
        <relationshipName>Original_Sales_Reps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Original_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Original Sales Rep</label>
    <nameField>
        <displayFormat>OSR-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Original Sales Rep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Original Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/OriginalSalesRepHandlerTest.cls
@isTest
private class OriginalSalesRepHandlerTest {

    static testMethod void testCreateOSR() {

        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Account testAccount = (Account)testData.get('Account');

        Test.startTest();
        Zuora__Subscription__c sub = TestClassUtility.createSubscription(false, testAccount);
        sub.Zuora__Version__c = 1;
        insert sub;
        Test.stopTest();

        List<Original_Sales_Rep__c> osrlist = [SELECT Id, Account__c, Original_Sales_Rep__c FROM Original_Sales_Rep__c 
                                              WHERE Account__c =: testAccount.id];
                                              
        system.assert(!osrlist.isEmpty());
    }

    static testMethod void testNotCreateOSR() {

        Map<String, SObject> testData =TestClassUtility.buildLocalData(false);
        Account testAccount = (Account)testData.get('Account');
        
        // exist subs with 12 months, and this will create one OSR records
        Zuora__Subscription__c sub1 = TestClassUtility.createSubscription(false, testAccount);
        sub1.Zuora__termstartdate__c = Date.today().addmonths(-4);
        sub1.Zuora__termenddate__c = Date.today().addmonths(-3);
        sub1.Zuora__Version__c = 1;
        insert sub1;

        Test.startTest();
        
        // exist subs with 12 months, and this will NOT create one OSR records
        Zuora__Subscription__c sub2 = TestClassUtility.createSubscription(false, testAccount);
        sub2.Zuora__termstartdate__c = Date.today();
        sub2.Zuora__termenddate__c = Date.today();
        insert sub2;
        Test.stopTest();

        List<Original_Sales_Rep__c> osrlist = [SELECT Id, Account__c, Original_Sales_Rep__c FROM Original_Sales_Rep__c 
                                              WHERE Account__c =: testAccount.id];

        System.assertEquals(osrlist.size(), 1);

    }
}