XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account_Snapshots__c.object
<CustomObject>
    <description>CSP-3326 30/60/90 Day on Cancel Saves</description>
    <fields>
        <fullName>Account_Value__c</fullName>
        <description>SUM(Zuora_MonthlyRecurringRevenue_c) for related Account when Commission_Line_Item_Status_c = Live</description>
        <label>Account Value</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Account Snapshots</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Account Snapshots Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipLabel>Live Subscription Product and Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pre_Zuora_MonthlyRecurringRevenue__c</fullName>
        <label>Pre Zuora MonthlyRecurringRevenue</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchCalculateAccountValueTest.cls
@isTest
private class BatchCalculateAccountValueTest {
    static testMethod void testCalculateAccountValue() {

		Account acc = TestClassUtility.createAccount(true);
		Contact con = TestClassUtility.createContact(true, acc);

		Case mockCase = TestClassUtility.createCase(true, acc, con) ;

        Live_Subscription__c liveSub = TestClassUtility.createLiveSub(true, acc);

        Live_Subscription_Product_and_Charge__c liveCharge = TestClassUtility.createliveCharge(true, acc, liveSub);

        Account_Snapshots__c accSnap = TestClassUtility.createAccSnap(true, mockCase);
	    			 
		Test.startTest();
        BatchCalculateAccountValue cls = new BatchCalculateAccountValue();
        Database.executeBatch(cls);
        Test.stopTest();

        Account_Snapshots__c assertAccSnap = [SELECT id, Account_Value__c FROM Account_Snapshots__c WHERE id =:accSnap.Id];
        system.assert(assertAccSnap.Account_Value__c == liveCharge.Pre_Zuora_MonthlyRecurringRevenue__c);

    }
}