XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_AM_Transfer__c</fullName>
        <description>Last date the Account Owner was changed to an Account Manager</description>
        <label>Last AM Transfer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Live_Stamp_Date__c</fullName>
        <label>Last Live $ Stamp Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_Stamp_Date__c</fullName>
        <label>Live $ Stamp Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Live_at_Every_Month__c</fullName>
        <description>Store the value from the start to the month before Last month</description>
        <label>Live at Every Month</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Live_at_Last_Month_Start__c</fullName>
        <description>CSP-3159 Last AM Transfer Date
Total Value of &quot;Live&quot; items as of the first of the last month</description>
        <label>Live $ at Last Month Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Live_at_Month_Start__c</fullName>
        <description>Total Value of &quot;Live&quot; items as of the first of the current month</description>
        <label>Live $ at Month Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VIP_Program__c</fullName>
        <description>CSP-1486
            Checked when customer has $15,000 or more in active subscriptions</description>
        <formula>(ISPICKVAL(Manual_VIP_Program_Status__c, &apos;VIP&apos;) || ActiveSubscriptionTCVSummary__c &gt;= 15000) &amp;&amp; NOT(ISPICKVAL(Manual_VIP_Program_Status__c, &apos;Not VIP&apos;))</formula>
        <label>VIP Program</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Line_Item_Status__c</fullName>
        <formula>IF(OR(CONTAINS(Name,&apos;#&apos; ),Name=&apos;CES Charge Migrated&apos;),
  &apos;Migrated&apos;,
  IF(NOT(Live_Subscription__r.Post_Is_Valid_Subscription__c), 
    &apos;Invalid&apos;,
    IF(Product_Type__c=&apos;Internet&apos;,
    If( And(Amement_Type__c=&apos;Remove Product&apos;,Zuora_EffectiveStartDate__c &gt;= Zuora_EffectiveEndDate__c),
      &apos;Removed&apos;,
      If(today()&lt;Zuora_EffectiveStartDate__c, 
        &apos;Pending&apos;,
        If(today()&lt;Zuora_EffectiveEndDate__c, 
          &apos;Live&apos;,
          If(Live_Subscription__r.Post_Zuora_Status__c=&apos;Cancelled&apos;, 
            &apos;Cancelled&apos;, 
            If( Amement_Type__c=&apos;Remove Product&apos;, 
              &apos;Removed&apos;,
              &apos;Expired&apos;
            ) 
          )
        )
      )
    ),    
      IF(Product_Type__c=&apos;Direct Mail&apos;,
        If(Live_Subscription__r.Post_Zuora_Status__c=&apos;Cancelled&apos;,
            &apos;Cancelled&apos;, 
      IF(Amement_Type__c=&apos;Remove Product&apos;, 
        &apos;Removed&apos;,
        If( OR(
            And(year(LDE_Email_Launch_Date__c)= year(today()),month(LDE_Email_Launch_Date__c)= month(today()),day(today())&gt;=2, day(LDE_Email_Launch_Date__c)&gt;1),
            And(year(AddMonths(LDE_Email_Launch_Date__c,1))= year(today()),month(AddMonths(LDE_Email_Launch_Date__c,1))= month(today()),day(today())=1,day(LDE_Email_Launch_Date__c)&gt;1 ),
            And(today()= LDE_Email_Launch_Date__c, day(LDE_Email_Launch_Date__c)=1),
            And(year(AddMonths(LDE_Email_Launch_Date__c,-1))= year(today()),month(AddMonths(LDE_Email_Launch_Date__c,-1))= month(today()),day(today())&gt;1,day(LDE_Email_Launch_Date__c)=1 )
          ), 
          &apos;Live&apos;,
          If( today() &lt; LDE_Email_Launch_Date__c, 
            &apos;Pending&apos;,
            &apos;Expired&apos;
          )
        )
      )
        ),
        IF(Product_Type__c =&apos;Print&apos;,
           IF(Live_Subscription__r.Post_Zuora_Status__c=&apos;Cancelled&apos;,
              &apos;Cancelled&apos;, 
        IF(Amement_Type__c=&apos;Remove Product&apos;, 
        &apos;Removed&apos;,
        If( OR(
            And(year(X1st_Cover_Date__c)= year(today()),month(X1st_Cover_Date__c)= month(today()),day(today())&gt;=2, day(X1st_Cover_Date__c)&gt;1),
            And(year(AddMonths(X1st_Cover_Date__c,1))= year(today()),month(AddMonths(X1st_Cover_Date__c,1))= month(today()),day(today())=1,day(X1st_Cover_Date__c)&gt;1 ),
            And(today()= X1st_Cover_Date__c, day(X1st_Cover_Date__c)=1),
            And(year(AddMonths(X1st_Cover_Date__c,-1))= year(today()),month(AddMonths(X1st_Cover_Date__c,-1))= month(today()),day(today())&gt;1,day(X1st_Cover_Date__c)=1 )
          ), 
          &apos;Live&apos;,
          IF(today() &lt; X1st_Cover_Date__c, 
          &apos;Pending&apos;,
          &apos;Expired&apos;
          )
        )
        )
          )
          ,&quot;Unknown&quot;
        )
      )
    )
  )
)</formula>
        <label>Commission Line Item Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Price__c</fullName>
        <formula>IF(Commission_Line_Item_Status__c=&apos;Live&apos;,
  IF(Product_Type__c =&apos;Internet&apos;, 
      Zuora_MonthlyRecurringRevenue__c,
      Zuora_TotalContractValue__c),
     null)</formula>
        <label>Live $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Live Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/BatchCalcLiveChargeTCVMonthly.cls
global class BatchCalcLiveChargeTCVMonthly implements Schedulable, Database.Batchable<sObject> {
    private String query;

    private static final String ACCOUNT_QUERY = 'SELECT ' 
                                                    + ' Id, '
                                                    + ' Last_AM_Transfer__c, '
                                                    + ' Live_at_Last_Month_Start__c, '
                                                    + ' Live_at_Every_Month__c, '
                                                    + ' Live_at_Month_Start__c, '
                                                    + ' Last_Live_Stamp_Date__c, '
                                                    + ' Live_Stamp_Date__c, '
                                                    + ' (Select '
                                                        +'Id, '
                                                        +'Live_Price__c, '
                                                        +'Product_Type__c '
                                                      +' From '
                                                        +'Live_Subscription_Product_and_Charges__r '
                                                      +'WHERE '
                                                        +' Commission_Line_Item_Status__c = \'Live\' AND Product_Type__c = \'Internet\') '
                                                + ' FROM '
                                                    +' Account '
                                                + ' WHERE '
                                                    + ' RecordType.Name = \'Local\' '
                                                  + ' AND '
                                                    + ' (Owner.Title =  \'Account Manager\' OR VIP_Program__c = TRUE)';


    global void execute(SchedulableContext sc) {
        Database.executeBatch(this);
    }

    global BatchCalcLiveChargeTCVMonthly() {
        query = ACCOUNT_QUERY;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

     /**
     * @purpose Calculate the live amount for the account which under the Account Manager
     * @author  Tony
     * @date    2018-10-22
     * @param   List<Account>  the local accounts under the account manager
     */
    global void execute(Database.BatchableContext BC, list<Account> scope) {
        List<Account> listAccountUpdate = new List<Account>();

        for (Account currentAccount :  scope) {
            Decimal tempLiveValue = 0;
            if (!currentAccount.Live_Subscription_Product_and_Charges__r.isEmpty()) {
                for (Live_Subscription_Product_and_Charge__c liveSPC : currentAccount.Live_Subscription_Product_and_Charges__r) {

                    Decimal lp = liveSPC.Live_Price__c!=null ? liveSPC.Live_Price__c:0;
                    tempLiveValue += lp;
                }
            }

            currentAccount.Live_at_Last_Month_Start__c = currentAccount.Live_at_Month_Start__c;
            currentAccount.Live_at_Month_Start__c = tempLiveValue;
            //Stamp calculate the live amount date
            currentAccount.Last_Live_Stamp_Date__c = currentAccount.Live_Stamp_Date__c;
            currentAccount.Live_Stamp_Date__c = System.today();
            listAccountUpdate.add(currentAccount);
        }
        if (!listAccountUpdate.isEmpty()) {

            Database.SaveResult[] updateResults = Database.update(listAccountUpdate, false);
            List<XO_Exception__C> exceptionList = ExceptionUtility.consumeException(updateResults);
            if(!exceptionList.isEmpty()){
                insert exceptionList;
            }
        }
        
    }

    global void finish(Database.BatchableContext BC) {

    }
}