XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__CustomerAccount__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Zuora__CustomerAccount__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/ZuoraSubscriptionUtilityTest.cls
@isTest
private class ZuoraSubscriptionUtilityTest {
	@isTest 
	static void testGenerateRenewalQuoteFromSubcription() {
		/////////////////////
		// BUILD TEST DATA //
		/////////////////////
		Test.startTest();
			Map<String, SObject> subData = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();

		subData.putAll(TestClassUtility.buildSubscriptionData((Account)subData.get('Account'), (Contact)subData.get('Contact'), (Opportunity)subData.get('Opportunity'), (Zuora__CustomerAccount__c)subData.get('Zuora__CustomerAccount__c')));

		// Get Subscription to send Id
		Zuora__Subscription__c createdSubscription = (Zuora__Subscription__c)subData.get('Zuora__Subscription__c');

		// Get Opportunity to send Id
		Opportunity createdOpportunity = (Opportunity)subData.get('Opportunity');

		// Call Zuora Subscription Utility class to generate renewal Quote from Subscription
		zqu__Quote__c generatedQuote = ZuoraSubscriptionUtility.generateRenewalQuoteFromSubscription(createdSubscription.Id, createdOpportunity);
	}

	@isTest
	static void testGenerateRenewalQuoteFromSubscriptionBatch() {
		/////////////////////
		// BUILD TEST DATA //
		/////////////////////
		Test.startTest();
			Map<String, SObject> subData = TestClassUtility.buildZQUTestObjects(false);
		Test.stopTest();

		subData.putAll(TestClassUtility.buildSubscriptionData((Account)subData.get('Account'), (Contact)subData.get('Contact'), (Opportunity)subData.get('Opportunity'), (Zuora__CustomerAccount__c)subData.get('Zuora__CustomerAccount__c')));

		// Get Subscription to send Id
		Zuora__Subscription__c createdSubscription = (Zuora__Subscription__c)subData.get('Zuora__Subscription__c');

		// Get Opportunity to send Id
		Opportunity createdOpportunity = (Opportunity)subData.get('Opportunity');

		Database.executeBatch(new BatchGenerateQuoteRatePlans(createdSubscription.Id, createdOpportunity), 1);
	}
}