XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>TestData</fullName>
        <active>true</active>
        <label>TestData</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lock_Quotes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lock Quotes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <inlineHelpText>Select the primary reason that the Opportunity was lost</inlineHelpText>
        <label>Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Advertises w/a competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Already Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel/ Re-enter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact not responsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currently not interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of non-payment terms and conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved of payment terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not contact again</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Improperly Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue w/T&amp;Cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Client Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No longer doing weddings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reason Given</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Issue/Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rep Issue/Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviews Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhappy w/Results</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Sales Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/OpportunityServiceTest.cls
@isTest
private class OpportunityServiceTest {

    static testMethod void testValidateOpportunityQuote(){

        TestClassUtility.DISABLE_TRIGGERS = TRUE;

        // for the error message data
        Account testAcc = TestClassUtility.createAccount(false);
        testAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Local').getRecordTypeId();
        insert testAcc;

        Contact testContact = TestClassUtility.createContact(true, testAcc);
        Generate_Quote_Pdf_Config__c testGQPdfC = TestClassUtility.generateQuotePdfConfig(true);
        // closed won error
        Opportunity testOpp1 = TestClassUtility.createOpportunity(false, testAcc, testContact);
        testOpp1.StageName = 'Closed Won';
        insert testOpp1;

        // closed lost error
        Opportunity testOpp2 = TestClassUtility.createOpportunity(false, testAcc, testContact);
        testOpp2.StageName = 'Closed Lost';
        testOpp2.Lost_Reason__c = 'expired';
        insert testOpp2;

        // locked quote error
        Opportunity testOpp3 = TestClassUtility.createOpportunity(false, testAcc, testContact);
        testOpp3.StageName = 'Quoting';
        testOpp3.Lock_Quotes__c = true;
        insert testOpp3;

        // null private contact role error
        Opportunity testOpp4 = TestClassUtility.createOpportunity(false, testAcc, testContact);
        testOpp4.StageName = 'Quoting';
        testOpp4.Lock_Quotes__c = false;
        insert testOpp4;


        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        
        List<String> listErrorMessage = new List<String>();

        Test.startTest();
        listErrorMessage.add(OpportunityService.validateOpportunityQuote(''));
        listErrorMessage.add(OpportunityService.validateOpportunityQuote(testOpp1.Id));
        listErrorMessage.add(OpportunityService.validateOpportunityQuote(testOpp2.Id));
        listErrorMessage.add(OpportunityService.validateOpportunityQuote(testOpp3.Id));
        listErrorMessage.add(OpportunityService.validateOpportunityQuote(testOpp4.Id));
        Test.stopTest();

        system.assertEquals('Invalid Opportunity ID Provided', listErrorMessage[0]);
        system.assertEquals(Label.Opportunity_Closed_Won_Reopen_Error, listErrorMessage[1]);
        system.assertEquals(Label.Opportunity_Closed_Lost_Reopen_Error, listErrorMessage[2]);
        system.assertEquals(Label.Opportunity_Locked_Warning_Message, listErrorMessage[3]);
        system.assertEquals(Label.Primary_Account_Contact_Role_Required_Warning_message, listErrorMessage[4]);
    }

    static testMethod void testValidateOpportunityQuoteNullService(){
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        // for the null active subs error
        Account testAcc1 = TestClassUtility.createAccount(false);
        testAcc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Local').getRecordTypeId();
        insert testAcc1;

        Contact testContact1 = TestClassUtility.createContact(true, testAcc1);
        AccountContactRole testAccountContactRole1 = TestClassUtility.createAccountContactRole(true, testAcc1, testContact1);

        Opportunity testOpp5 = TestClassUtility.createOpportunity(false, testAcc1, testContact1);
        testOpp5.StageName = 'Quoting';
        testOpp5.Lock_Quotes__c = false;
        insert testOpp5;

        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        List<String> listErrorMessage = new List<String>();

        Test.startTest();
        listErrorMessage.add(OpportunityService.validateOpportunityQuote(testOpp5.Id));

        Test.stopTest();

        system.assertEquals(Label.Cancel_Reenter_Need_a_Active_Subscription, listErrorMessage[0]);

    }

    static testMethod void testValidateOpportunityQuoteNoError(){
        TestClassUtility.DISABLE_TRIGGERS = TRUE;

        // for the success quote
        Map<String,SObject> testData = TestClassUtility.buildLocalData(true);
        Opportunity testOpp6 = (Opportunity)testData.get('Opportunity');

        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        
        List<String> listErrorMessage = new List<String>();

        Test.startTest();
        listErrorMessage.add(OpportunityService.validateOpportunityQuote(testOpp6.Id));
        Test.stopTest();

        system.assertEquals('', listErrorMessage[0]);
    }
}