XO_Project_UAT/Project--XOGrp--UAT/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Pre_RSD_Id__c</fullName>
        <label>Pre RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Version__c</fullName>
        <label>Subscription Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>RSD_Id__c</fullName>
        <label>RSD ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N40000001lGjTEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__ChargeNumber__c</fullName>
        <description>The charge number for this charge.</description>
        <label>Charge Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Subscription__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__Version__c</fullName>
        <description>The version of the rate plan charge. Each time a charge is amended, Zuora creates a new version of the rate plan charge.</description>
        <label>Version</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/LiveSubscriptionPCTriggerTest.cls
@isTest
private class LiveSubscriptionPCTriggerTest {
    @testSetup static void buildTestData() {
        Account testAccount = TestClassUtility.createAccount(true);
        Zuora__Subscription__c testSubscription = TestClassUtility.createSubscription(false,testAccount);
        testSubscription.Zuora__Version__c = 1;
        insert testSubscription;

        Zuora__SubscriptionProductCharge__c testSubscriptionPC1 = TestClassUtility.createSubscriptionProductCharge(false,testAccount,testSubscription);
        testSubscriptionPC1.Zuora__ChargeNumber__c = 'testSubscriptionPC1';
        testSubscriptionPC1.Zuora__Account__c = testAccount.id;
        testSubscriptionPC1.RSD_Id__c = '123';
        insert testSubscriptionPC1;

    }

    static testMethod void testLiveSUbscriptionUpdate() {
        

        Live_Subscription_Product_and_Charge__c newLiveSubscriptionPC  = [select Id,Subscription_Version__c from Live_Subscription_Product_and_Charge__c limit 1];
        newLiveSubscriptionPC.Subscription_Version__c = 2;
        
        Test.startTest();
        update newLiveSubscriptionPC;
        Test.stopTest();

        Live_Subscription_Product_and_Charge__c liveSubscriptionPCAfterUpdate = [Select id,Pre_RSD_Id__c from Live_Subscription_Product_and_Charge__c where id =: newLiveSubscriptionPC.Id];
        system.assertNotEquals(liveSubscriptionPCAfterUpdate.Pre_RSD_Id__c, null);
    }

    static testMethod void testLiveSUbscriptionDelete() {

        Live_Subscription_Product_and_Charge__c newLiveSubscriptionPC  = [select Id from Live_Subscription_Product_and_Charge__c limit 1];

        Test.startTest();
        delete newLiveSubscriptionPC;
        Test.stopTest();

        List<Live_Subscription_Product_and_Charge__c> listliveSubscriptionPCAfterDelete = [Select id from Live_Subscription_Product_and_Charge__c];
        system.assertEquals(0, listliveSubscriptionPCAfterDelete.size());
    }
}