XO_Project_UAT/Project--XOGrp--UAT/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Notify_Sales_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify Sales Team</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Notify_Sales_Team__c</fullName>
        <formula>Campaign.Notify_Sales_Team__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notify Sales Team</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DE_Backlog__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SS-4768</description>
        <label>DE Backlog</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/CampaignMemberTriggerHandlerTest.cls
@isTest
private class CampaignMemberTriggerHandlerTest {
    static testMethod void testMethod1() {
      test.startTest();
        lead testLead = TestClassUtility.createLead(false);
        testLead.DE_Backlog__c = true;
        insert testLead;

        Campaign testCam = new Campaign();
        testCam.Notify_Sales_Team__c = true;
        // testCam.Active = true;
        testCam.Name = 'Test Campaign';
        insert testCam;

        CampaignMember testCamMem = new CampaignMember();
        testCamMem.CampaignId = testCam.Id;
        testCamMem.LeadId = testLead.Id;
        // testCamMem.Name = 'test';
        insert testCamMem;

        update testCamMem;

        delete testCamMem;
      test.stopTest();
    }
    static testMethod void testMethod2() {
      test.startTest();
        lead testLead = TestClassUtility.createLead(false);
        testLead.DE_Backlog__c = true;
        insert testLead;

        Campaign testCam = new Campaign();
        testCam.Notify_Sales_Team__c = true;
        // testCam.Active = true;
        testCam.Name = 'Paid Media';
        testCam.Type = 'Paid Media';
        insert testCam;

        CampaignMember testCamMem = new CampaignMember();
        testCamMem.CampaignId = testCam.Id;
        testCamMem.LeadId = testLead.Id;
        // testCamMem.Name = 'test';
        insert testCamMem;

        update testCamMem;

        delete testCamMem;
      test.stopTest();
    }

     static testMethod void testMethod3() {
      test.startTest();

        lead testLead = TestClassUtility.createLead(false);
        testLead.DE_Backlog__c = true;
        insert testLead;

        Campaign testCam = new Campaign();
        testCam.Notify_Sales_Team__c = false;
        // testCam.Active = true;
        testCam.Name = 'Paid Media';
        testCam.Type = 'Paid Media';
        insert testCam;

        CampaignMember testCamMem = new CampaignMember();
        testCamMem.CampaignId = testCam.Id;
        testCamMem.LeadId = testLead.Id;
        // testCamMem.Name = 'test';
        insert testCamMem;

        update testCamMem;

        delete testCamMem;
      test.stopTest();
    }
}