XO_Project_UAT/Project--XOGrp--UAT/src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category_Code__c</fullName>
        <externalId>true</externalId>
        <label>Category Code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Destination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SubCategory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Category ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_Description__c</fullName>
        <inlineHelpText>This field is copy of Short description and will be updated automatically if it&apos;s blank.</inlineHelpText>
        <label>Zuora Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Category_Group__c</fullName>
        <formula>text(Primary_Category__r.Category_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Negative_Disposition_Reason__c</fullName>
        <description>csp-2440</description>
        <label>Negative Disposition Reason</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Verify Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No contact information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor outside US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Timeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed Claim Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Required Information</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <formula>IF( text(Local_Sales_Market__r.Country__c ) = &apos;CA&apos;, &apos;Senior Sales Executive&apos;, Text(Zip__r.Portfolio__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_Details__c</fullName>
        <description>csp-1940</description>
        <label>Reason Details</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zip</label>
        <referenceTo>Zip__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Local</label>
    </recordTypes>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <businessProcess>Local</businessProcess>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Local_Sales_Rep_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Local Sales Rep Assignments</relationshipLabel>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Local_Sales_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Local Sales Rep Assignment</label>
    <nameField>
        <label>Local Sales Rep Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Sales Rep Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Market ID</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market_Tier__c</fullName>
        <label>Market Tier</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a sales rep</errorMessage>
            <filterItems>
                <field>User.Division</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_Description__c</fullName>
        <inlineHelpText>This field is copy of Short description and will be updated automatically if it&apos;s blank.</inlineHelpText>
        <label>Zuora Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zip__c.object
<CustomObject>
    <fields>
        <fullName>Local_Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Zips</relationshipLabel>
        <relationshipName>Zips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MetroArea__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metro Area</label>
        <referenceTo>MetroArea__c</referenceTo>
        <relationshipLabel>Zips</relationshipLabel>
        <relationshipName>Zips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>The Portfolio is a grouping logic for Zip codes that offers a more refined distinguishing of zip codes from Markets. Will flow up to the account and lead objects based off of the zip code relationship that is saved on each one.</description>
        <inlineHelpText>Portfolio&apos;s should be used as a submarket relationship and a zip can only be related to one portfolio.</inlineHelpText>
        <label>Portfolio</label>
        <picklist>
            <picklistValues>
                <fullName>Senior Sales Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <externalId>true</externalId>
        <label>Zip Code (External ID)</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zip</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/LeadDomainTest.cls
@isTest
public class LeadDomainTest {

    // TODO: this method will be moved to a test data factory after making some more refinements 
    public static List<Lead> testDataSetup(Integer numberOfLeads) {
        
        Market__c testMarket = TestClassUtility.createMarket(false);
        testMarket.Active__c = true;
        insert testMarket;

        Category__c testCategory = TestClassUtility.createCategory(false);
        testCategory.Category_Group__c = 'Primary';
        testCategory.Active__c = true;
        testCategory.Name = 'Reception Venues - REC';
        insert testCategory;

        List<Lead> newLeadsList = new List<Lead>();

        for(Integer index=0; index < numberOfLeads; index++) {
            newLeadsList.add(TestClassUtility.createLead(false, testMarket, testCategory));
        }
        return newLeadsList;
    }

    @isTest 
    public static void leadRoutingAfterCleansingTest() {
        Profile testDataTeamProfile = [SELECT Id FROM Profile WHERE Name = 'Local Sales Data Team' LIMIT 1];
        User testDataTeamUser = TestClassUtility.createUser(true, testDataTeamProfile);

        Market__c testMarket = TestClassUtility.createMarket(false);
        testMarket.Name = 'OH - Toledo - 208';
        testMarket.Market_ID__c = '208';
        testMarket.Market_Tier__c = 'C';
        testMarket.Short_Description__c = 'OH-Toledo';
        testMarket.Active__c = true;
        insert testMarket;

        Category__c testCategory = TestClassUtility.createCategory(false);
        testCategory.Category_Group__c = 'Primary';
        testCategory.Active__c = true;
        testCategory.Name = 'Bridal Salons - BWP';
        testCategory.Category_ID__c = '585';
        testCategory.Category_Code__c = 'BWP';
        testCategory.Zuora_Description__c = 'Bridal Salons';   
        testCategory.Short_Description__c = 'Bridal Salons';   
        insert testCategory;

        List<Local_Sales_Rep_Assignment__c> localSalesRepAssignmentList = new List<Local_Sales_Rep_Assignment__c>();       
        Local_Sales_Rep_Assignment__c localSalesRepAssignment = TestClassUtility.createLocalSalesRepAssignment(false, testCategory, testMarket, null);
        localSalesRepAssignment.Sales_Rep__c = UserInfo.getUserId();
        localSalesRepAssignmentList.add(localSalesRepAssignment);
        insert localSalesRepAssignmentList;

        System.runAs(testDataTeamUser){
            Lead testLead = TestClassUtility.createLead(false, testMarket, testCategory);
            testLead.Status = 'Invalid';
            testLead.Negative_Disposition_Reason__c = 'Other';
            testLead.Reason_Details__c = 'test';
            insert testLead;
        
            Test.startTest();

                testLead.Status = 'Valid';
                testLead.Negative_Disposition_Reason__c = null;
                testLead.Reason_Details__c = null;
                update testLead;
            
            Test.stopTest();
        
            List<Lead> listLeadsAssert = [SELECT OwnerId FROM Lead WHERE Id =: testLead.Id];
            System.assert(!listLeadsAssert.isEmpty());
            System.assertEquals(localSalesRepAssignment.Sales_Rep__c, listLeadsAssert[0].OwnerId);
        }
    }
    
    @isTest 
    public static void phoneValidationInvalidTest() {
       
        List<Lead> testLeadsList = testDataSetup(2);

        if(testLeadsList.size() > 0) {
            testLeadsList[0].Phone =  '1231231231';
            testLeadsList[1].Phone = '77777qweqwe';
        }

        try {
            insert testLeadsList;
        } catch(Exception e) {
            System.Assert(e.getMessage().contains('Phone should be in the format of (###) ###-####. Please correct before saving.'));
        }
    }

    @isTest
    public static void leadConvertTest() {
        
        List<Lead> testLeadsList = testDataSetup(2);
        Lead leadRec = testLeadsList[0];
        leadRec.Website = 'www.spacexone.com';
        leadRec.Phone = '3453453456';
        leadRec.Email = 'goforit@gmail.com';
        insert testLeadsList;

        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(leadRec.id);
        lc.setDoNotCreateOpportunity(false);
        lc.setConvertedStatus('Qualified');
        lc.setOwnerId(UserInfo.getUserId());

        Event evnt = new Event(WhoId = leadRec.Id, Subject = 'Test Lead Conversion');

        Test.startTest();
            Database.LeadConvertResult lcr = Database.convertLead(lc);

            FeedItem testFeed = New FeedItem();
            testFeed.ParentId = testLeadsList[0].id;
            testFeed.Title = 'test title';
            testFeed.Body = 'Hello';
            testFeed.LinkUrl = 'www.abc123.com';
            insert testFeed;

            LeadDomain domain = new LeadDomain();
            FeedItem feedItemRec = domain.createNewFeed(leadRec.ConvertedAccountId, testFeed);
        Test.stopTest();

        System.assert(lcr.isSuccess());
        System.assertEquals(feedItemRec.Title, testFeed.Title, 'Both titles should be same as we are cloning the feed');
    }

    @isTest
    public static void qualifyLeadNegativeTest() {
        List<Lead> testLeadsList = testDataSetup(2);
        testLeadsList[0].LastName = 'Last Name';
        insert testLeadsList;

        Test.startTest();
            try {
                LeadDomain domain = new LeadDomain();
                domain.qualifyLead(testLeadsList[0]);
            } catch (Exception e) {
                // failure expected here as we are passing junk last name to the method 
                System.assert(e.getMessage().contains('LastName cannot be a junk value')); 
            }
        Test.stopTest();
    }

    @isTest
    public static void createAssignmentHistoryRecords() {

        List<Lead> leadList = new List<Lead>();

        Market__c testMarket = TestClassUtility.createMarket(false);
        testMarket.Active__c = true;
        insert testMarket;

        Category__c testCategory = TestClassUtility.createCategory(false);
        testCategory.Category_Group__c = 'Primary';
        testCategory.Active__c = true;
        testCategory.Name = 'Reception Venues - REC';
        insert testCategory;

        MetroArea__c ma = TestClassUtility.createMetroArea(true);
        
        Zip__c testzip = TestClassUtility.createZip(false);
        testzip.MetroArea__c = ma.id;
        testzip.ZipCode__c = '94230';
        testzip.name = '94230';
        testzip.Local_Market__c = testMarket.id;
        testzip.Portfolio__c = 'Senior Sales Executive';
        insert testzip;

        Lead testLead = TestClassUtility.createLead(false, testMarket, testCategory);
        testLead.Phone = '1231231231';
        testLead.CountryCode = 'US';
        testLead.PostalCode = testZip.ZipCode__c;
        testLead.OwnerId = UserInfo.getUserId();
        leadList.add(testLead);

        Lead testLead2 = TestClassUtility.createLead(false, testMarket, testCategory);
        testLead2.Phone = '8888888888';
        testLead.CountryCode = 'US';
        testLead.PostalCode = 'pppppppp';
        leadList.add(testLead2);

        List<Local_Sales_Rep_Assignment__c> localSalesRepAssignmentList = new List<Local_Sales_Rep_Assignment__c>();       
        Local_Sales_Rep_Assignment__c lsra = TestClassUtility.createLocalSalesRepAssignment(false, testCategory, testMarket, null);
        localSalesRepAssignmentList.add(lsra);
        insert localSalesRepAssignmentList;

        Test.startTest();
            LeadDomain domain = new LeadDomain();
            domain.createAssignmentHistoryRecords(localSalesRepAssignmentList[0].Id, leadList[0]);
        Test.stopTest();

        Assignment_History__c assignmentHistoryRec = [Select Id from Assignment_History__c where Local_Sales_Rep_Assignment__c =: lsra.Id];
        System.assert(assignmentHistoryRec != null); // this means assignment history records were created which is the job of this function
    }
}