XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <formula>IF(TODAY()&lt;Switch_Date__c, Pre_AutoRenewal__c, Post_AutoRenewal__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AutoRenewal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Is_Valid_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Post Is Valid Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Zuora_TermEndDate__c</fullName>
        <label>Post Zuora Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Name__c</fullName>
        <externalId>true</externalId>
        <label>Subscription Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Switch_Date__c</fullName>
        <label>Switch Date</label>
        <type>Date</type>
    </fields>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipLabel>Live Subscription Product and Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <label>Market ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Switch_Date__c</fullName>
        <label>Switch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora_ChargeNumber__c</fullName>
        <externalId>true</externalId>
        <label>Zuora Charge Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora_EffectiveEndDate__c</fullName>
        <label>Zuora EffectiveEndDate</label>
        <type>Date</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <label>AutoRenewal</label>
        <picklist>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancel_Reenter_Original_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cancel Reenter Original Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Quotes (Cancel Reenter Original Subscription)</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_Not_Remove_Amendment__c</fullName>
        <label>Count Of Not Remove Amendment</label>
        <summaryFilterItems>
            <field>zqu__QuoteAmendment__c.zqu__Type__c</field>
            <operation>notEqual</operation>
            <value>RemoveProduct</value>
        </summaryFilterItems>
        <summaryForeignKey>zqu__QuoteAmendment__c.zqu__Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Count_of_Quote_Charge_Detail__c</fullName>
        <label>Count of Quote Charge Detail</label>
        <summaryForeignKey>zqu__QuoteChargeDetail__c.zqu__Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Count_of_Remove_Amendment__c</fullName>
        <label>Count of Remove Amendment</label>
        <summaryFilterItems>
            <field>zqu__QuoteAmendment__c.zqu__Type__c</field>
            <operation>equals</operation>
            <value>RemoveProduct</value>
        </summaryFilterItems>
        <summaryForeignKey>zqu__QuoteAmendment__c.zqu__Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Order_Type1__c</fullName>
        <label>Order Type 1</label>
        <picklist>
            <picklistValues>
                <fullName>First Internet Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Print Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal(Original)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal(New)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Reenter(Original)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Reenter(New)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Direct Mail Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment(Removal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Qualified New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Type2__c</fullName>
        <label>Order Type 2</label>
        <picklist>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta Zero</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_Subscription_CMRR__c</fullName>
        <label>Original Subscription CMRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Subscription_TCV__c</fullName>
        <label>Original Subscription TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Being_Renewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Being Renewed</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Quotes (Renewal Dashboard Subscription)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__InitialTerm__c</fullName>
        <description>The Initial Term of the Quote.</description>
        <inlineHelpText>The Initial Term of the Quote.</inlineHelpText>
        <label>Initial Term</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Previewed_Delta_MRR__c</fullName>
        <description>The Contracted Delta MRR returned by previewing the quote in Zuora</description>
        <inlineHelpText>Delta MRR which is got by previewing the quote from Zuora.</inlineHelpText>
        <label>Delta MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Previewed_MRR__c</fullName>
        <description>The Contracted MRR returned by previewing the quote in Zuora</description>
        <inlineHelpText>MRR value which is got by previewing the quote from Zuora. TEST</inlineHelpText>
        <label>MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>Market_ID__c</fullName>
        <description>SF-1821</description>
        <label>Market ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>SF-612</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>AutoRenewal__c</fullName>
        <description>for CSP-1786</description>
        <label>AutoRenewal</label>
        <picklist>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Type1__c</fullName>
        <label>Order Type 1</label>
        <picklist>
            <picklistValues>
                <fullName>Renewal(Original)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Quote which originally created this Subscription before any amendments.</description>
        <inlineHelpText>This is the Quote which originally created this Subscription before any amendments.</inlineHelpText>
        <label>Original Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428</description>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zuora__Zuora_Id__c</fullName>
        <description>The Zuora Id (external primary key) of this Subscription.</description>
        <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
        <label>Zuora Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/TransactionTaggingHandlerTest.cls
@isTest
private class TransactionTaggingHandlerTest {


    @testSetup static void buildTestActiveSubData(){
        
        TestClassUtility.DISABLE_TRIGGERS = TRUE;

        List<RecordType> localRecordTypeList = [SELECT Id, Name, SObjectType FROM RecordType WHERE Name LIKE '%local%' AND IsActive = true];
        Map<String, Id> localRecordTypeMap = new Map<String, Id>();
        for(Integer i = 0; i < localRecordTypeList.size(); i++) {
          RecordType currentRecordType = localRecordTypeList[i];
          localRecordTypeMap.put(currentRecordType.SObjectType, currentRecordType.Id);
        }
        Generate_Quote_Pdf_Config__c testGQPdfC = TestClassUtility.generateQuotePdfConfig(true);


        // for active subs data
        Account testAccount = TestClassUtility.createAccount(false);
        testAccount.RecordTypeId = localRecordTypeMap.get('Account');
        testAccount.Name = 'test Account for Active Sub';
        insert testAccount;

        Contact testContact = TestClassUtility.createContact(true, testAccount);

        Opportunity testOpp = TestClassUtility.createOpportunity(false, testAccount, testContact);
        testOpp.StageName = 'Quoting';
        insert testOpp;

        Zuora__Subscription__c testActiveSub = TestClassUtility.createSubscription(false,testAccount);
        testActiveSub.Zuora__External_Id__c = 'subfortestquotetriggerhandler1';
        testActiveSub.Zuora__Zuora_Id__c = 'subfortestquotetriggerhandler1';
        testActiveSub.Product_Line__c = 'Internet';
        testActiveSub.AutoRenewal__c = 'YES';
        testActiveSub.Zuora__TermStartDate__c = Date.today();
        testActiveSub.Zuora__TermEndDate__c = Date.today().adddays(365);
        insert testActiveSub;

        Zuora__Subscription__c testActiveSub1 = TestClassUtility.createSubscription(false,testAccount);
        testActiveSub1.Zuora__External_Id__c = 'subfortestquotetriggerhandler2';
        testActiveSub1.Zuora__Zuora_Id__c = 'subfortestquotetriggerhandler2';
        testActiveSub1.Product_Line__c = 'Print';
        testActiveSub1.AutoRenewal__c = 'YES';
        testActiveSub1.Zuora__TermStartDate__c = Date.today();
        testActiveSub1.Zuora__TermEndDate__c = Date.today().adddays(365);
        insert testActiveSub1;

        Live_Subscription__c testActiveLiveSub = TestClassUtility.createLiveSub(false,testAccount);
        testActiveLiveSub.Post_Is_Valid_Subscription__c = true;
        testActiveLiveSub.Switch_Date__c = Date.today();
        testActiveLiveSub.Post_Zuora_TermEndDate__c = Date.today().adddays(100);
        testActiveLiveSub.Product_Line__c = 'Internet';
        insert testActiveLiveSub;

        Live_Subscription_Product_and_Charge__c testAcitveLiveCharge = TestClassUtility.createliveCharge(true,testAccount,testActiveLiveSub);

        Live_Subscription__c testActiveLiveSub1 = TestClassUtility.createLiveSub(false,testAccount);
        testActiveLiveSub1.Post_Is_Valid_Subscription__c = true;
        testActiveLiveSub1.Subscription_Name__c = 's-000002';
        testActiveLiveSub1.Switch_Date__c = Date.today();
        testActiveLiveSub1.Post_Zuora_TermEndDate__c = Date.today().adddays(190);
        testActiveLiveSub1.Product_Line__c = 'Print';
        insert testActiveLiveSub1;

        Live_Subscription_Product_and_Charge__c testAcitveLiveCharge1 = TestClassUtility.createliveCharge(false,testAccount,testActiveLiveSub1);
        testAcitveLiveCharge1.Zuora_ChargeNumber__c = 'c-000002';
        testAcitveLiveCharge1.Product_Type__c = 'Print';
        testAcitveLiveCharge1.Market_ID__c = '202';
        testAcitveLiveCharge1.Zuora_EffectiveEndDate__c = Date.today().adddays(190);
        insert testAcitveLiveCharge1;

        Live_Subscription_Product_and_Charge__c testAcitveLiveCharge2 = TestClassUtility.createliveCharge(false,testAccount,testActiveLiveSub1);
        testAcitveLiveCharge2.Zuora_ChargeNumber__c = 'c-000003';
        testAcitveLiveCharge2.Market_ID__c = '202';
        testAcitveLiveCharge2.Zuora_EffectiveEndDate__c = Date.today().adddays(250);
        insert testAcitveLiveCharge2;


        // for expired subs data
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;

        Account testAccount1 = TestClassUtility.createAccount(false);
        testAccount1.RecordTypeId = localRecordTypeMap.get('Account');
        testAccount1.Name = 'test Account for Expired Sub';
        Database.SaveResult srAccount1 = Database.insert(testAccount1, dml);

        Contact testContact1 = TestClassUtility.createContact(false, testAccount1);
        Database.SaveResult srContact1 = Database.insert(testContact1, dml);

        Opportunity testOpp1 = TestClassUtility.createOpportunity(false, testAccount1, testContact1);
        testOpp1.StageName = 'Quoting';
        insert testOpp1;

        Zuora__Subscription__c testExpiredSub = TestClassUtility.createSubscription(false,testAccount1);
        testExpiredSub.Zuora__External_Id__c = 'subfortestquotetriggerhandlere';
        testExpiredSub.Zuora__Zuora_Id__c = 'subfortestquotetriggerhandlere';
        testExpiredSub.Product_Line__c = 'Direct Mail';
        testExpiredSub.AutoRenewal__c = 'YES';
        testExpiredSub.Zuora__TermStartDate__c = Date.today().adddays(-100);
        testExpiredSub.Zuora__TermEndDate__c = Date.today().adddays(-10);
        insert testExpiredSub;

        // for expired than 12 monts subs data
        Account testAccount2 = TestClassUtility.createAccount(false);
        testAccount2.RecordTypeId = localRecordTypeMap.get('Account');
        testAccount2.Name = 'test Account for No Sub';
        Database.SaveResult srAccount2 = Database.insert(testAccount2, dml);

        Contact testContact2 = TestClassUtility.createContact(false, testAccount2);
        Database.SaveResult srContact2 = Database.insert(testContact2, dml);

        Opportunity testOpp2 = TestClassUtility.createOpportunity(false, testAccount2, testContact2);
        testOpp2.StageName = 'Quoting';
        insert testOpp2;

        Zuora__Subscription__c testExpired12Sub = TestClassUtility.createSubscription(false,testAccount2);
        testExpired12Sub.Zuora__External_Id__c = 'subfortestquotetriggerhandler12';
        testExpired12Sub.Zuora__Zuora_Id__c = 'subfortestquotetriggerhandler12';
        testExpired12Sub.Product_Line__c = 'Direct Mail';
        testExpired12Sub.AutoRenewal__c = 'YES';
        testExpired12Sub.Zuora__TermStartDate__c = Date.today().addmonths(-24);
        testExpired12Sub.Zuora__TermEndDate__c = Date.today().addmonths(-13);
        insert testExpired12Sub;

        TestClassUtility.DISABLE_TRIGGERS = FALSE;
    }


    static testMethod void testAssignTransactionTagForNewSubWrapper() {
        Set<Id> accountIdSet = new Set<Id>();

        Account testAccount = [SELECT Id,(SELECT Id FROM Opportunities LIMIT 1), 
                                        (SELECT Id FROM Contacts LIMIT 1),
                                        (SELECT Id FROM Zuora__Subscriptions__r WHERE Product_Line__c = 'Internet' limit 1) 
                                    FROM Account WHERE Name = 'test Account for Active Sub'];

        
        accountIdSet.add(testAccount.Id);
        
        //   for exist market Print
        zqu__Quote__c testZquQuote = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote.Product_Line__c = 'Print';
        testZquQuote.zqu__InitialTerm__c = 12;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote.Original_Subscription_CMRR__c = 10;
        testZquQuote.Order_Type1__c = '';
        testZquQuote.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote;

        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge = new zqu__QuoteRatePlanCharge__c();
        testQuoteRatePlanCharge.Market_ID__c = '101';

        List<zqu__QuoteRatePlanCharge__c> listQRPC = new List<zqu__QuoteRatePlanCharge__c>();
        listQRPC.add(testQuoteRatePlanCharge);

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw.quote = testZquQuote;
        qw.quote.zqu__Previewed_MRR__c = 10;
        qw.quoteId = testZquQuote.Id;
        qw.quoteProductLine = 'Print';
        qw.quoteSubscriptionType = 'New Subscription';
        qw.quoteRatePlanChargeListMap.put(testZquQuote.Id,listQRPC);


        //   for new market Print
        zqu__Quote__c testZquQuote1 = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote1.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote1.Product_Line__c = 'Print';
        testZquQuote1.zqu__InitialTerm__c = 12;
        testZquQuote1.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote1.Original_Subscription_CMRR__c = 10;
        testZquQuote1.Order_Type1__c = '';
        testZquQuote1.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote1;

        zqu__QuoteRatePlanCharge__c testQuoteRatePlanCharge1 = new zqu__QuoteRatePlanCharge__c();
        testQuoteRatePlanCharge1.Market_ID__c = '202';

        List<zqu__QuoteRatePlanCharge__c> listQRPC1 = new List<zqu__QuoteRatePlanCharge__c>();
        listQRPC1.add(testQuoteRatePlanCharge1);

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw1 = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw1.quote = testZquQuote1;
        qw1.quote.zqu__Previewed_MRR__c = 20;
        qw1.quoteId = testZquQuote1.Id;
        qw1.quoteProductLine = 'Print';
        qw1.quoteSubscriptionType = 'New Subscription';
        qw1.quoteRatePlanChargeListMap.put(testZquQuote1.Id,listQRPC1);

        //   for Internet
        zqu__Quote__c testZquQuote2 = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote2.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote2.Product_Line__c = 'Internet';
        testZquQuote2.zqu__InitialTerm__c = 12;
        testZquQuote2.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote2.Original_Subscription_CMRR__c = 10;
        testZquQuote2.Order_Type1__c = '';
        testZquQuote2.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote2;

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw2 = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw2.quote = testZquQuote2;
        qw2.quote.zqu__Previewed_MRR__c = 20;
        qw2.quoteId = testZquQuote2.Id;
        qw2.quoteProductLine = 'Internet';
        qw2.quoteSubscriptionType = 'New Subscription';



        Test.startTest();
        TransactionTaggingHandler.buildDataMap(accountIdSet);
        qw = TransactionTaggingHandler.assignTransactionTag(qw);
        qw1 = TransactionTaggingHandler.assignTransactionTag(qw1);
        qw2 = TransactionTaggingHandler.assignTransactionTag(qw2);
        Test.stopTest();

        system.assertEquals(1, TransactionTaggingHandler.mapAccountIdToSubEndDate.size());
        system.assertEquals(2, TransactionTaggingHandler.mapKeyStrToEndDate.size());

        system.assertEquals('Upsell',qw2.quote.Order_Type2__c);

        system.assertEquals('First Print Sale',qw.quote.Order_Type1__c);
        system.assertEquals('',qw1.quote.Order_Type1__c);
        system.assertEquals('',qw2.quote.Order_Type1__c);
    }


    static testMethod void testAssignTransactionTagForWrapper() {
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        Account testAccount = [SELECT Id,(SELECT Id FROM Opportunities LIMIT 1), (SELECT Id FROM Contacts LIMIT 1) FROM Account WHERE Name = 'test Account for Active Sub'];
        //   for all remove  
        zqu__Quote__c testZquQuote = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote.zqu__SubscriptionType__c = 'Amend Subscription';
        testZquQuote.Product_Line__c = 'Internet';
        testZquQuote.zqu__InitialTerm__c = 12;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote.zqu__Previewed_Delta_MRR__c = 0;
        insert testZquQuote;

        zqu__QuoteChargeDetail__c testQuoteChargeDetail = new zqu__QuoteChargeDetail__c();
        testQuoteChargeDetail.zqu__Quote__c = testZquQuote.id;
        insert testQuoteChargeDetail;

        zqu__QuoteAmendment__c testQuoteAmendment = new zqu__QuoteAmendment__c();
        testQuoteAmendment.zqu__Quote__c = testZquQuote.id;
        testQuoteAmendment.zqu__Type__c = 'RemoveProduct';
        insert testQuoteAmendment;

        zqu__Quote__c testZquQuoteData = [SELECT Id,Count_of_Quote_Charge_Detail__c,Count_of_Remove_Amendment__c,Order_Type1__c,Order_Type2__c,
                                                    Subscription_Being_Renewed__c,Cancel_Reenter_Original_Subscription__c,Original_Subscription_CMRR__c, 
                                                    Original_Subscription_TCV__c, Count_Of_Not_Remove_Amendment__c,zqu__Previewed_Delta_MRR__c,
                                                    zqu__Previewed_Delta_TCV__c  
                                                FROM zqu__Quote__c 
                                                WHERE Id =: testZquQuote.Id];

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw.quote = testZquQuoteData;
        qw.quote.zqu__Previewed_Delta_MRR__c = 0;
        qw.quoteId = testZquQuoteData.Id;
        qw.quoteProductLine = 'Internet';
        qw.quoteSubscriptionType = 'Amend Subscription';


        // for only remove
        zqu__Quote__c testZquQuote1 = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote1.zqu__SubscriptionType__c = 'Amend Subscription';
        testZquQuote1.Product_Line__c = 'Internet';
        testZquQuote1.zqu__InitialTerm__c = 12;
        testZquQuote1.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote1.zqu__Previewed_Delta_MRR__c = -10;
        insert testZquQuote1;

        zqu__QuoteChargeDetail__c testQuoteChargeDetail1 = new zqu__QuoteChargeDetail__c();
        testQuoteChargeDetail1.zqu__Quote__c = testZquQuote1.id;
        insert testQuoteChargeDetail1;

        zqu__QuoteChargeDetail__c testQuoteChargeDetail11 = new zqu__QuoteChargeDetail__c();
        testQuoteChargeDetail11.zqu__Quote__c = testZquQuote1.id;
        insert testQuoteChargeDetail11;

        zqu__QuoteAmendment__c testQuoteAmendment1 = new zqu__QuoteAmendment__c();
        testQuoteAmendment1.zqu__Quote__c = testZquQuote1.id;
        testQuoteAmendment1.zqu__Type__c = 'RemoveProduct';
        insert testQuoteAmendment1;

        zqu__Quote__c testZquQuoteData1 = [SELECT Id,Count_of_Quote_Charge_Detail__c,Count_of_Remove_Amendment__c,Order_Type1__c,Order_Type2__c,
                                                    Subscription_Being_Renewed__c,Cancel_Reenter_Original_Subscription__c,Original_Subscription_CMRR__c, 
                                                    Original_Subscription_TCV__c, Count_Of_Not_Remove_Amendment__c,zqu__Previewed_Delta_MRR__c,
                                                    zqu__Previewed_Delta_TCV__c  
                                                FROM zqu__Quote__c 
                                                WHERE Id =: testZquQuote1.Id];

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw1 = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw1.quote = testZquQuoteData1;
        qw1.quote.zqu__Previewed_Delta_MRR__c = -10;
        qw1.quoteId = testZquQuoteData1.Id;
        qw1.quoteProductLine = 'Internet';
        qw1.quoteSubscriptionType = 'Amend Subscription';

        // for update
        zqu__Quote__c testZquQuote2 = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote2.zqu__SubscriptionType__c = 'Amend Subscription';
        testZquQuote2.Product_Line__c = 'Internet';
        testZquQuote2.zqu__InitialTerm__c = 12;
        testZquQuote2.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote2.zqu__Previewed_Delta_MRR__c = 10;
        insert testZquQuote2;

        zqu__QuoteChargeDetail__c testQuoteChargeDetail2 = new zqu__QuoteChargeDetail__c();
        testQuoteChargeDetail2.zqu__Quote__c = testZquQuote2.id;
        insert testQuoteChargeDetail2;

        zqu__QuoteChargeDetail__c testQuoteChargeDetail21 = new zqu__QuoteChargeDetail__c();
        testQuoteChargeDetail21.zqu__Quote__c = testZquQuote2.id;
        insert testQuoteChargeDetail21;

        zqu__QuoteAmendment__c testQuoteAmendment2 = new zqu__QuoteAmendment__c();
        testQuoteAmendment2.zqu__Quote__c = testZquQuote2.id;
        testQuoteAmendment2.zqu__Type__c = 'AddProduct';
        insert testQuoteAmendment2;

        zqu__Quote__c testZquQuoteData2 = [SELECT Id,Count_of_Quote_Charge_Detail__c,Count_of_Remove_Amendment__c,Order_Type1__c,Order_Type2__c,
                                                    Subscription_Being_Renewed__c,Cancel_Reenter_Original_Subscription__c,Original_Subscription_CMRR__c, 
                                                    Original_Subscription_TCV__c, Count_Of_Not_Remove_Amendment__c,zqu__Previewed_Delta_MRR__c,
                                                    zqu__Previewed_Delta_TCV__c  
                                                FROM zqu__Quote__c 
                                                WHERE Id =: testZquQuote2.Id];

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw2 = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw2.quote = testZquQuoteData2;
        qw2.quote.zqu__Previewed_Delta_MRR__c = 10;
        qw2.quoteId = testZquQuoteData2.Id;
        qw2.quoteProductLine = 'Internet';
        qw2.quoteSubscriptionType = 'Amend Subscription';

        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        Test.startTest();
        qw = TransactionTaggingHandler.assignTransactionTag(qw);
        qw1 = TransactionTaggingHandler.assignTransactionTag(qw1);
        qw2 = TransactionTaggingHandler.assignTransactionTag(qw2);
        Test.stopTest();

        system.assertEquals('Removal',qw.quote.Order_Type1__c);
        system.assertEquals('Delta Zero',qw.quote.Order_Type2__c);

        system.assertEquals('Amendment(Removal)',qw1.quote.Order_Type1__c);
        system.assertEquals('Downsell',qw1.quote.Order_Type2__c);

        system.assertEquals('Amendment',qw2.quote.Order_Type1__c);
        system.assertEquals('Upsell',qw2.quote.Order_Type2__c);
    }


    static testMethod void testAssignTransactionTagForCancelReenterWrapper() {
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        Account testAccount = [SELECT Id,(SELECT Id FROM Opportunities LIMIT 1), 
                                        (SELECT Id FROM Contacts LIMIT 1),
                                        (SELECT Id FROM Zuora__Subscriptions__r WHERE Product_Line__c = 'Internet' limit 1) 
                                    FROM Account WHERE Name = 'test Account for Active Sub'];
        

        //   for cancel reenter delta zero
        zqu__Quote__c testZquQuote = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote.Product_Line__c = 'Internet';
        testZquQuote.zqu__InitialTerm__c = 12;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote.Original_Subscription_CMRR__c = 10;
        testZquQuote.Order_Type1__c = 'Cancel Reenter(New)';
        testZquQuote.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote;

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw.quote = testZquQuote;
        qw.quote.zqu__Previewed_MRR__c = 10;
        qw.quoteId = testZquQuote.Id;
        qw.quoteProductLine = 'Internet';
        qw.quoteSubscriptionType = 'New Subscription';


        //   for cancel reenter upsell
        zqu__Quote__c testZquQuote1 = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote1.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote1.Product_Line__c = 'Internet';
        testZquQuote1.zqu__InitialTerm__c = 12;
        testZquQuote1.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote1.Original_Subscription_CMRR__c = 10;
        testZquQuote1.Order_Type1__c = 'Cancel Reenter(New)';
        testZquQuote1.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote1;


        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw1 = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw1.quote = testZquQuote1;
        qw1.quote.zqu__Previewed_MRR__c = 20;
        qw1.quoteId = testZquQuote1.Id;
        qw1.quoteProductLine = 'Internet';
        qw1.quoteSubscriptionType = 'Cancel Reenter(New)';

        // for cancel reenter downSell
        zqu__Quote__c testZquQuote2 = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote2.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote2.Product_Line__c = 'Internet';
        testZquQuote2.zqu__InitialTerm__c = 12;
        testZquQuote2.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote2.Original_Subscription_CMRR__c = 20;
        testZquQuote2.Order_Type1__c = 'Cancel Reenter(New)';
        testZquQuote2.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote2;

        ZuoraTCVAndPaymentSchedule.QuotesWrapper qw2 = new ZuoraTCVAndPaymentSchedule.QuotesWrapper();
        qw2.quote = testZquQuote2;
        qw2.quote.zqu__Previewed_MRR__c = 10;
        qw2.quoteId = testZquQuote2.Id;
        qw2.quoteProductLine = 'Internet';
        qw2.quoteSubscriptionType = 'Cancel Reenter(New)';

        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        Test.startTest();
        qw = TransactionTaggingHandler.assignTransactionTag(qw);
        qw1 = TransactionTaggingHandler.assignTransactionTag(qw1);
        qw2 = TransactionTaggingHandler.assignTransactionTag(qw2);
        Test.stopTest();


        system.assertEquals('Delta Zero',qw.quote.Order_Type2__c);

        system.assertEquals('Upsell',qw1.quote.Order_Type2__c);

        system.assertEquals('Downsell',qw2.quote.Order_Type2__c);
    }

    static testMethod void testIsNewSubscription() {
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        Account testAccount = [SELECT Id,(SELECT Id FROM Opportunities LIMIT 1), 
                                        (SELECT Id FROM Contacts LIMIT 1),
                                        (SELECT Id FROM Zuora__Subscriptions__r WHERE Product_Line__c = 'Internet' limit 1) 
                                    FROM Account WHERE Name = 'test Account for Active Sub'];
        

        //   for cancel reenter delta zero
        zqu__Quote__c testZquQuote = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote.Product_Line__c = 'Internet';
        testZquQuote.zqu__InitialTerm__c = 12;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote.Original_Subscription_CMRR__c = 10;
        testZquQuote.Order_Type1__c = 'Cancel Reenter(New)';
        testZquQuote.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote;

        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        Test.startTest();
        Boolean isNewSubscription = TransactionTaggingHandler.isNewSubscription(testZquQuote);

        Test.stopTest();

        system.assertEquals(false,isNewSubscription);
    }
    
    static testMethod void testIsFirstSale(){
        TestClassUtility.DISABLE_TRIGGERS = TRUE;
        Account testAccount = [SELECT Id,(SELECT Id FROM Opportunities LIMIT 1), 
                                        (SELECT Id FROM Contacts LIMIT 1),
                                        (SELECT Id FROM Zuora__Subscriptions__r WHERE Product_Line__c = 'Internet' limit 1) 
                                    FROM Account WHERE Name = 'test Account for Active Sub'];
        

        //   for cancel reenter delta zero
        zqu__Quote__c testZquQuote = TestClassUtility.createQuote(false,testAccount.Opportunities[0],testAccount,testAccount.Contacts[0]);
        testZquQuote.zqu__SubscriptionType__c = 'New Subscription';
        testZquQuote.Product_Line__c = 'Internet';
        testZquQuote.zqu__InitialTerm__c = 11;
        testZquQuote.zqu__TermStartDate__c = Date.today().adddays(1);
        testZquQuote.Original_Subscription_CMRR__c = 10;
        testZquQuote.Order_Type1__c = 'Cancel Reenter(New)';
        testZquQuote.Cancel_Reenter_Original_Subscription__c = testAccount.Zuora__Subscriptions__r[0].Id;
        insert testZquQuote;

        TestClassUtility.DISABLE_TRIGGERS = FALSE;

        Test.startTest();
        Boolean isFirstSale = TransactionTaggingHandler.isFirstSale(testZquQuote, 'Test String');

        Test.stopTest();

        system.assertEquals(false,isFirstSale);
    }
}