XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid_Subscription__c</fullName>
        <formula>Post_Is_Valid_Subscription__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Valid Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_Account__c</fullName>
        <formula>IF(TODAY()&lt;Switch_Date__c, Pre_Zuora_Account__c, Post_Zuora_Account__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zuora Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_TermEndDate__c</fullName>
        <formula>IF(TODAY()&lt;Switch_Date__c, Pre_Zuora_TermEndDate__c, Post_Zuora_TermEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zuora Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription_Product_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipLabel>Live Subscription Product and Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market_ID__c</fullName>
        <label>Market ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zuora_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Live Charges</relationshipLabel>
        <relationshipName>Live_Subscription_Product_and_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zuora_EffectiveEndDate__c</fullName>
        <label>Zuora EffectiveEndDate</label>
        <type>Date</type>
    </fields>
    <label>Live Subscription Product and Charge</label>
    <nameField>
        <label>Live Subscription Product and Charge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscription Product and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Cancel_Reenter_Original_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cancel Reenter Original Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Quotes (Cancel Reenter Original Subscription)</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_Of_Not_Remove_Amendment__c</fullName>
        <label>Count Of Not Remove Amendment</label>
        <summaryFilterItems>
            <field>zqu__QuoteAmendment__c.zqu__Type__c</field>
            <operation>notEqual</operation>
            <value>RemoveProduct</value>
        </summaryFilterItems>
        <summaryForeignKey>zqu__QuoteAmendment__c.zqu__Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Count_of_Quote_Charge_Detail__c</fullName>
        <label>Count of Quote Charge Detail</label>
        <summaryForeignKey>zqu__QuoteChargeDetail__c.zqu__Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Count_of_Remove_Amendment__c</fullName>
        <label>Count of Remove Amendment</label>
        <summaryFilterItems>
            <field>zqu__QuoteAmendment__c.zqu__Type__c</field>
            <operation>equals</operation>
            <value>RemoveProduct</value>
        </summaryFilterItems>
        <summaryForeignKey>zqu__QuoteAmendment__c.zqu__Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <formula>TEXT(zqu__Opportunity__r.StageName)</formula>
        <label>Opportunity Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type1__c</fullName>
        <label>Order Type 1</label>
        <picklist>
            <picklistValues>
                <fullName>First Internet Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Print Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal(Original)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal(New)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Reenter(Original)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Reenter(New)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Direct Mail Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment(Removal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Qualified New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Type2__c</fullName>
        <label>Order Type 2</label>
        <picklist>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta Zero</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_Subscription_CMRR__c</fullName>
        <label>Original Subscription CMRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Subscription_TCV__c</fullName>
        <label>Original Subscription TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>SF-1428. Used to filter what products are shown in the Quote creation workflow process.</description>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Being_Renewed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Being Renewed</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Quotes (Renewal Dashboard Subscription)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>True_TCV__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>(CSP-1181) Used to replace Zuora&apos;s out-of-the-box TCV functionality since it doesn&apos;t work properly in all cases</description>
        <label>True TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>zqu__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account associated with this Quote.</description>
        <inlineHelpText>The Account associated with this Quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__InitialTerm__c</fullName>
        <description>The Initial Term of the Quote.</description>
        <inlineHelpText>The Initial Term of the Quote.</inlineHelpText>
        <label>Initial Term</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Previewed_Delta_MRR__c</fullName>
        <description>The Contracted Delta MRR returned by previewing the quote in Zuora</description>
        <inlineHelpText>Delta MRR which is got by previewing the quote from Zuora.</inlineHelpText>
        <label>Delta MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Previewed_Delta_TCV__c</fullName>
        <description>Delta TCV which is got by previewing the quote from Zuora</description>
        <inlineHelpText>Delta TCV which is got by previewing the quote from Zuora.</inlineHelpText>
        <label>Delta TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Previewed_MRR__c</fullName>
        <description>The Contracted MRR returned by previewing the quote in Zuora</description>
        <inlineHelpText>MRR value which is got by previewing the quote from Zuora. TEST</inlineHelpText>
        <label>MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__Previewed_TCV__c</fullName>
        <description>TCV value which is got by previewing the quote from Zuora</description>
        <inlineHelpText>TCV value which is got by previewing the quote from Zuora.</inlineHelpText>
        <label>TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__QuoteRatePlanCharge__c.object
<CustomObject>
    <description>A QuoteRatePlanCharge, like QuoteRatePlan, is part of a Quote.</description>
    <fields>
        <fullName>Market_ID__c</fullName>
        <description>SF-1821</description>
        <label>Market ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>True_TCV__c</fullName>
        <description>CSP-1334</description>
        <label>True TCV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Quote Rate Plan Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Rate Plan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/TransactionTaggingHandler.cls
public without sharing class TransactionTaggingHandler {

    public static Map<Id, Date> mapAccountIdToSubEndDate = new Map<Id,Date>();
    public static Map<Id, Date> mapInternetSub = new Map<Id,Date>();
    public static Map<String,Date> mapKeyStrToEndDate = new Map<String,Date>();

    /**
     * @purpose generate the static data to calculate the order type 1 and order type 2 of the quote
     * @author  Tony Liu
     * @date    2018-10-11
     * @param   Set account id set
     * @return  null
     */
    public static void buildDataMap(Set<Id> accountIdSet) {

        List<Live_Subscription_Product_and_Charge__c> listLSPC = [SELECT Id,Market_ID__c,Zuora_EffectiveEndDate__c, Zuora_Account__c,
                                                                        Live_Subscription__r.Zuora_TermEndDate__c, Live_Subscription__r.Product_Line__c
                                                                FROM Live_Subscription_Product_and_Charge__c 
                                                                WHERE Zuora_Account__c IN : accountIdSet 
                                                                    AND Live_Subscription__r.Is_Valid_Subscription__c = TRUE 
                                                                ORDER BY Live_Subscription__r.Zuora_TermEndDate__c DESC]; 

        if (!listLSPC.isEmpty()) {
            for (Live_Subscription_Product_and_Charge__c lspc:  listLSPC) {
                
                if (!mapAccountIdToSubEndDate.containsKey(lspc.Zuora_Account__c)){
                    mapAccountIdToSubEndDate.put(lspc.Zuora_Account__c, lspc.Live_Subscription__r.Zuora_TermEndDate__c);
                }

                if(!mapInternetSub.containsKey(lspc.Zuora_Account__c) && lspc.Live_Subscription__r.Product_Line__c == 'Internet'){
                    mapInternetSub.put(lspc.Zuora_Account__c, lspc.Live_Subscription__r.Zuora_TermEndDate__c);
                }

                Id accountId = lspc.Zuora_Account__c;
                
                String productLine = lspc.Live_Subscription__r.Product_Line__c;
                String keyString = accountId + productLine;

                if (lspc.Live_Subscription__r.Product_Line__c != 'Print') {
                                        
                    if (!mapKeyStrToEndDate.containsKey(keyString)) {
                        mapKeyStrToEndDate.put(keyString, lspc.Live_Subscription__r.Zuora_TermEndDate__c);
                    }
                    
                }else{

                    keyString += lspc.Market_ID__c;

                    if(!mapKeyStrToEndDate.containsKey(keyString)){
                        mapKeyStrToEndDate.put(keyString,lspc.Zuora_EffectiveEndDate__c);
                    }else if (mapKeyStrToEndDate.get(keyString) < lspc.Zuora_EffectiveEndDate__c) {
                        mapKeyStrToEndDate.put(keyString,lspc.Zuora_EffectiveEndDate__c);
                    }
                }
            }
        }
    }

    /**
     * @purpose assign order type 1 and order type 2 for the quote which is cancel reenter/renewal
     * @author  Tony Liu
     * @date    2018-10-11
     * @param   Wrapperclass ZuoraTCVAndPaymentSchedule.QuotesWrapper
     * @return  Wrapperclass ZuoraTCVAndPaymentSchedule.QuotesWrapper
     */
    public static ZuoraTCVAndPaymentSchedule.QuotesWrapper assignTransactionTag(ZuoraTCVAndPaymentSchedule.QuotesWrapper qw) {

        if (qw.quoteSubscriptionType == 'Amend Subscription' 
            && qw.quote.Count_of_Quote_Charge_Detail__c == qw.quote.Count_of_Remove_Amendment__c) {

            qw.quote.Order_Type1__c = 'Removal';
        }
        else if (qw.quoteSubscriptionType == 'Amend Subscription' && qw.quote.Count_Of_Not_Remove_Amendment__c == 0) {
            qw.quote.Order_Type1__c = 'Amendment(Removal)';
        }
        else if (qw.quoteSubscriptionType == 'Amend Subscription') {
            qw.quote.Order_Type1__c = 'Amendment';
        }

        // if the quote is renewal(new) or Cancel Reenter(New), we should compare the mrr with the mrr of the original subs
        if ( qw.quote.Order_Type1__c == 'Renewal(New)' 
                && (String.isNotBlank(qw.quote.Subscription_Being_Renewed__c) )
            || ( qw.quote.Order_Type1__c == 'Cancel Reenter(New)' 
                && String.isNotBlank(qw.quote.Cancel_Reenter_Original_Subscription__c) ) ) {
            
            if ( (qw.quoteProductLine == 'Internet' && qw.quote.zqu__Previewed_MRR__c > qw.quote.Original_Subscription_CMRR__c) || 
                    (qw.quoteProductLine != 'Internet' && qw.quote.zqu__Previewed_TCV__c > qw.quote.Original_Subscription_TCV__c)) {

                qw.quote.Order_Type2__c = 'Upsell';
            } 
            else if ( (qw.quoteProductLine == 'Internet' && qw.quote.zqu__Previewed_MRR__c == qw.quote.Original_Subscription_CMRR__c) || 
                    (qw.quoteProductLine != 'Internet' && qw.quote.zqu__Previewed_TCV__c == qw.quote.Original_Subscription_TCV__c)) {
                
                qw.quote.Order_Type2__c = 'Delta Zero';
            } 
            else if ( (qw.quoteProductLine == 'Internet' && qw.quote.zqu__Previewed_MRR__c < qw.quote.Original_Subscription_CMRR__c) || 
                    (qw.quoteProductLine != 'Internet' && qw.quote.zqu__Previewed_TCV__c < qw.quote.Original_Subscription_TCV__c)) {
                
                qw.quote.Order_Type2__c = 'Downsell';
            }

        }
        // if the quote is amend, we should check the delta MRR(For Internet) or delta TCV(For Print and LDE)
        else if (qw.quoteSubscriptionType == 'Amend Subscription') {
            if ((qw.quoteProductLine == 'Internet' && qw.quote.zqu__Previewed_Delta_MRR__c > 0 ) || 
                    (qw.quoteProductLine != 'Internet' && qw.quote.zqu__Previewed_Delta_TCV__c > 0 )) {

                qw.quote.Order_Type2__c = 'Upsell';
            }
            else if ((qw.quoteProductLine == 'Internet' && qw.quote.zqu__Previewed_Delta_MRR__c == 0 ) || 
                    (qw.quoteProductLine != 'Internet' && qw.quote.zqu__Previewed_Delta_TCV__c == 0 )) {

                qw.quote.Order_Type2__c = 'Delta Zero';
            }
            else if ((qw.quoteProductLine == 'Internet' && qw.quote.zqu__Previewed_Delta_MRR__c < 0 ) || 
                    (qw.quoteProductLine != 'Internet' && qw.quote.zqu__Previewed_Delta_TCV__c < 0 )) {

                qw.quote.Order_Type2__c = 'Downsell';
            }
        }

        if (qw.quoteSubscriptionType == 'New Subscription' 
            && qw.quote.Order_Type1__c != 'Renewal(New)' 
            && qw.quote.Order_Type1__c != 'Cancel Reenter(New)'){
            
            Id accountId = qw.quote.zqu__Account__c;
            // set the Order_Type2__c to amend when the quote is new subscription but not cancel reenter(new) and renewal
            if (mapAccountIdToSubEndDate.containsKey(qw.quote.zqu__Account__c)) {

                Date originalSubLatestEnd = mapAccountIdToSubEndDate.get(qw.quote.zqu__Account__c);
                
                if(qw.quoteProductLine == 'Internet'){
                    assignOrderType2(qw, originalSubLatestEnd);
                }
                else{
                    // if there is an active subscription under the account, set the Order_Type2__c to upsell
                    if (originalSubLatestEnd >= Date.today()) {
                        qw.quote.Order_Type2__c = 'Upsell';
                    }
                    // if there is no active subscription under the account and the latest subs has been expired/cancelled in one year, 
                    // set the Order_Type2__c to Winback
                    else if (originalSubLatestEnd < Date.today() 
                        && originalSubLatestEnd > qw.quote.zqu__TermStartDate__c.addmonths(-12)) {
                        
                        qw.quote.Order_Type2__c = 'Winback';
                    }
                    else{
                        qw.quote.Order_Type2__c = '';
                    }
                }
            }

            if(qw.quoteProductLine == 'Internet'){
                
                assignOrderType1(qw);
                System.debug(LoggingLevel.INFO, '*** qw: ' + qw.quote);
            }
            else if (qw.quoteProductLine == 'Print') {
                String tempOrderType1 = 'First Print Sale';
                for (List<zqu__QuoteRatePlanCharge__c> listQRPC : qw.quoteRatePlanChargeListMap.values()) {
                    for (zqu__QuoteRatePlanCharge__c qrpc:  listQRPC) {
                        String printKeyString = accountId + qw.quote.Product_Line__c + qrpc.Market_ID__c;
                        if (!isFirstSale(qw.quote,printKeyString)){
                            tempOrderType1 = '';
                            break;
                        }
                    }
                }
            
                qw.quote.Order_Type1__c = tempOrderType1;
            }
            else{
                String keyString = accountId + qw.quote.Product_Line__c;
                if (isFirstSale(qw.quote, keyString)) {
                    qw.quote.Order_Type1__c = 'First ' +qw.quote.Product_Line__c+' Sale';
                }
                else{
                    qw.quote.Order_Type1__c = '';
                }
            } 
        }

        return qw;
    }

    /**
     * @purpose Check the quote is the first sale for the product line on the account
     * @author  Tony Liu
     * @date    2018-10-11
     * @param   object   zqu_quote
     * @param   String   keyString, generate by accountId + product line
     * @return  Boolean
     */
    public static Boolean isFirstSale(Zqu__Quote__c zquQuoteObj, String keyString){

        Boolean checkFirstSale = true;

        // check the first sale for the quote only initial term greater than 12 months
        if (zquQuoteObj.zqu__InitialTerm__c < 12 || 
            ( mapKeyStrToEndDate.containsKey(keyString) && 
                mapKeyStrToEndDate.get(keyString) >= Date.today().addmonths(-12) ) ) {
            
            checkFirstSale = false;
        }


        return checkFirstSale;
    }

   
    /**
     * @purpose Determine if the Quote is used for new subscription
     * @author  Tony Liu
     * @date    2018-10-12
     * @param   Object Quote currentQuote 
     * @return  Boolean is the Quote new Sub or not
     */
    public static Boolean isNewSubscription(Zqu__Quote__c currentQuote) {
        return (currentQuote.Opportunity_Stage__c == 'Calculating TCV' 
            && currentQuote.zqu__SubscriptionType__c == 'New Subscription' 
            && currentQuote.Order_Type1__c != 'Renewal(New)' 
            && currentQuote.Order_Type1__c != 'Cancel Reenter(New)');
    }

    /**
    * @description it's used to determine if the quote initial term greater equal than 12 or not
    * @param Zqu__Quote__c the current Quote
    *
    * @return Boolean true if the quote initial term greater equal than 12 months otherwise false
    */
    public static Boolean InitialTermGreaterEqualThan12(Zqu__Quote__c currentQuote){
        return currentQuote.zqu__InitialTerm__c >= 12;
    }
    
    /**
    * @description it's used to determine if there are any active live subs or not
    * @param Zqu__Quote__c the current Quote
    * @param Date the latest live subscription term start date
    * 
    * @return Boolean true if there are any active live subs otherwise false
    */
    public static Boolean hasActiveLiveSub(Zqu__Quote__c currentQuote, Date originalSubLatestEnd){

        if(originalSubLatestEnd!=NULL){
            return originalSubLatestEnd >= currentQuote.zqu__TermStartDate__c;
        }
        else{
            return false;
        }
    }
    
    /**
    * @description it's used to determine if there are any expired or cancelled live subs within 12 months
    * @param Zqu__Quote__c the current Quote
    * @param Date the latest live subscription term start date
    * 
    * @return Boolean true if there are any expired or cancelled live subs within 12 months otherwise false
    */
    public static Boolean hasExpiredCancelledLiveSubWithin12(Zqu__Quote__c currentQuote, Date originalSubLatestEnd){

        if(originalSubLatestEnd!=NULL){
            return !hasActiveLiveSub(currentQuote, originalSubLatestEnd) && 
                    (originalSubLatestEnd >= currentQuote.zqu__TermStartDate__c.addmonths(-12));
        }
        else{
            return false;
        }
    }
    
    /**
    * @description it's used to determine if the Quote true TCV greater than 0 or not
    * @param Zqu__Quote__c the current Quote
    * 
    * @return Boolean true if the Quote true TCV greater than 0 otherwise false
    */
    public static Boolean trueTCVGreaterThan0(Zqu__Quote__c currentQuote){
        return currentQuote.True_TCV__c > 0;
    }
    
    /**
    * @description it's used to assign the Order type 2 with appropriate value
    * @param ZuoraTCVAndPaymentSchedule.QuotesWrapper Quote Wrapper
    * @param Date the latest live subscription term start date
    * 
    */
    public static void assignOrderType2(ZuoraTCVAndPaymentSchedule.QuotesWrapper qw, Date originalSubLatestEnd){
        
        if(hasActiveLiveSub(qw.quote,originalSubLatestEnd)){
            qw.quote.Order_Type2__c = 'Upsell';
        }
        else{
            if(hasExpiredCancelledLiveSubWithin12(qw.quote,originalSubLatestEnd)){
                qw.quote.Order_Type2__c = 'Winback';
            }
        }
    }
    
    /**
    * @description it's used to assign the Order type 1 with appropriate value
    * @param ZuoraTCVAndPaymentSchedule.QuotesWrapper Quote Wrapper
    * 
    */
    public static void assignOrderType1(ZuoraTCVAndPaymentSchedule.QuotesWrapper qw){
        
        Date internetSubLatestEnd = null;

        System.debug(LoggingLevel.INFO, '*** mapInternetSub: ' + mapInternetSub);
        System.debug(LoggingLevel.INFO, '*** qw.quote.zqu__Account__c: ' + qw.quote.zqu__Account__c);
        if(mapInternetSub.containsKey(qw.quote.zqu__Account__c)){
            internetSubLatestEnd = mapInternetSub.get(qw.quote.zqu__Account__c);
        }

        if(qw.quoteProductLine == 'Internet'){
            System.debug(LoggingLevel.INFO, '*** qw.quote: qw.quote');
            System.debug(LoggingLevel.INFO, '*** internetSubLatestEnd: '+ internetSubLatestEnd);

            if(!hasActiveLiveSub(qw.quote,internetSubLatestEnd) && !hasExpiredCancelledLiveSubWithin12(qw.quote,internetSubLatestEnd)){
            
                if(InitialTermGreaterEqualThan12(qw.quote)){
                    
                    if(trueTCVGreaterThan0(qw.quote)){
                        qw.quote.Order_Type1__c = 'First Internet Sale';
                    }
                    else{
                        if(qw.hasTradeDiscountReason){
                            qw.quote.Order_Type1__c = 'First Internet Sale';
                        }
                        else{
                            qw.quote.Order_Type1__c = 'Non-Qualified New';
                        }
                    }
                }
                else{
                    qw.quote.Order_Type1__c = 'Non-Qualified New';
                }
            }
        }
        else{
            qw.quote.Order_Type1__c = 'First Internet Sale';
        }
    }
}