XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Residual_Subscription_Name__c</fullName>
        <label>Residual Subscription Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Residual_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipName>Residuals_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PayeeName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Originating_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PayeeStartDate__c</fullName>
        <label>Payee Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PayeeType__c</fullName>
        <label>Payee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Residual Sales Rep</label>
    <nameField>
        <displayFormat>Payee-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Payee Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residual Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/XO_Exception__c.object
<CustomObject>
    <label>XO Exception</label>
    <nameField>
        <label>XO Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Exception</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/ResidualSalesRepMaintainHandler.cls
public with sharing class ResidualSalesRepMaintainHandler {
    
    // the map stores residual subscription name with live subscription
    private static Map<String, Live_Subscription__c> mapResidualSubsForRenewalAndReenter = new Map<String, Live_Subscription__c>();

    /**
     * set value to mapResidualSubsForRenewalAndReenter
     * 
     * @return void
     */
    public static void setResidualSubsMap(String residualSubName, Live_Subscription__c ls){
        if(!mapResidualSubsForRenewalAndReenter.containskey(residualSubName)){
            mapResidualSubsForRenewalAndReenter.put(residualSubName, ls);
        }
    }

    /**
     * Create residual sales rep records from renewal or cancel re-enter
     * 
     * @return void
     */
    public static void createResidualSalesReps(){
        
        List<Residual_Sales_Rep__c> listRSRforInsert = new List<Residual_Sales_Rep__c>();
        List<XO_Exception__c> xoExceptionList = new List<XO_Exception__c>();
        
        if(!mapResidualSubsForRenewalAndReenter.isEmpty()){

            List<Residual_Sales_Rep__c> reslist = [SELECT Id, PayeeName__c, PayeeStartDate__c, PayeeType__c, Live_Subscription__r.Name, Live_Subscription__r.Residual_Subscription_Name__c FROM 
                                                Residual_Sales_Rep__c WHERE Live_Subscription__r.Name IN: mapResidualSubsForRenewalAndReenter.keyset()];
            
            if(!reslist.isEmpty()){
                for(Residual_Sales_Rep__c rsr: reslist){
                    
                    String rsName = rsr.Live_Subscription__r.Name;
                    if(mapResidualSubsForRenewalAndReenter.containskey(rsName)){

                        Id resId = mapResidualSubsForRenewalAndReenter.get(rsName).Id;
                        Residual_Sales_Rep__c resSalesRep = new Residual_Sales_Rep__c();
                        resSalesRep.Live_Subscription__c = resId;
                        resSalesRep.PayeeName__c = rsr.PayeeName__c;
                        resSalesRep.PayeeStartDate__c = rsr.PayeeStartDate__c; 
                        resSalesRep.PayeeType__c = rsr.PayeeType__c;

                        listRSRforInsert.add(resSalesRep);
                    }
                }
            }
        }
        
        if(!listRSRforInsert.isEmpty()){
            List<Database.SaveResult> resultList = Database.insert(listRSRforInsert, false);
            xoExceptionList.addAll(ExceptionUtility.consumeException(resultList));
        }
        
    }
}