XO_Project_UAT/Project--XOGrp--UAT/src/objects/Live_Subscription__c.object
<CustomObject>
    <label>Live Subscription</label>
    <nameField>
        <label>Live Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Residual_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Live_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live Subscription</label>
        <referenceTo>Live_Subscription__c</referenceTo>
        <relationshipName>Residuals_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PayeeName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Originating_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PayeeStartDate__c</fullName>
        <label>Payee Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PayeeType__c</fullName>
        <label>Payee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Residual Sales Rep</label>
    <nameField>
        <displayFormat>Payee-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Payee Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residual Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/ResidualSalesRepMaintainHandlerTest.cls
@isTest
private class ResidualSalesRepMaintainHandlerTest {

    static testMethod void DoNotCreateRSR() {
        
        Map<String, SObject> mapData = TestClassUtility.buildLocalData(true);
        
        List<Live_Subscription__c> liveSubList = [SELECT Id FROM Live_Subscription__c];


        Test.startTest();

        ResidualSalesRepMaintainHandler.setResidualSubsMap('Test Residual Sub', liveSubList[0]);
        ResidualSalesRepMaintainHandler.createResidualSalesReps();

        Test.stopTest();

        List<Residual_Sales_Rep__c> resList = [SELECT Id FROM Residual_Sales_Rep__c];
        
        System.assert(resList.isEmpty());

    }

    static testMethod void createRSR() {
        
        Map<String, SObject> mapData = TestClassUtility.buildLocalData(true);
        
        List<Live_Subscription__c> liveSubList = [SELECT Id, OwnerId, Name FROM Live_Subscription__c];
        
        Residual_Sales_Rep__c rsr = new Residual_Sales_Rep__c();
        rsr.Live_Subscription__c = liveSubList[0].id;
        rsr.PayeeName__c = liveSubList[0].OwnerId;
        rsr.PayeeStartDate__c = Date.today();
        rsr.PayeeType__c = 'test';

        insert rsr;

        Test.startTest();

        ResidualSalesRepMaintainHandler.setResidualSubsMap(liveSubList[0].Name, liveSubList[0]);
        ResidualSalesRepMaintainHandler.createResidualSalesReps();

        Test.stopTest();

        List<Residual_Sales_Rep__c> resList = [SELECT Id FROM Residual_Sales_Rep__c];
        System.assert(!resList.isEmpty());
    }

}