XO_Project_UAT/Project--XOGrp--UAT/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact who signs the contract in EchoSign.</inlineHelpText>
        <label>Contract Signer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EchoSign_Contract_Due_Date__c</fullName>
        <description>SF-1509 and SF-1502. When the Opportunity stage is changed to &quot;Pending Client Approval&quot; the OpportunityTrigger sets this for three business days from now.</description>
        <inlineHelpText>This is the latest date that the EchoSign contract can be sent in order to provide the customer with five full business days to sign.</inlineHelpText>
        <label>EchoSign Contract Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lock_Quotes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lock Quotes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_of_Times_To_Extend__c</fullName>
        <defaultValue>0</defaultValue>
        <description>It used to stored extend times to auto close</description>
        <label># of Times To Extend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Expiration_Date__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Local&apos;, Today() + 60, null)</defaultValue>
        <description>Used to determine when the Opportunity will expire and the inventory associated to this Opportunity will be released.</description>
        <label>Opportunity Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Three_Business_Days_From_Today__c</fullName>
        <description>Used in &quot;Send For Signature&quot; validation</description>
        <label>EchoSign Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/zqu__Quote__c.object
<CustomObject>
    <description>The Quotes related to an Opportunity.</description>
    <fields>
        <fullName>Cancel_Reenter_Cancel_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cancel Reenter(Cancel) Quote</label>
        <referenceTo>zqu__Quote__c</referenceTo>
        <relationshipLabel>Quotes (Cancel Reenter(Cancel) Quote)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exist_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exist Subscription</label>
        <referenceTo>Zuora__Subscription__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRepLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact that is billed for this Quote.</description>
        <inlineHelpText>The Contact that is billed for this Quote.</inlineHelpText>
        <label>Bill to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity associated with this Quote.</description>
        <inlineHelpText>The Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SoldToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact that is sold to for this Quote.</description>
        <inlineHelpText>The Contact that is sold to for this Quote.</inlineHelpText>
        <label>Sold to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes (Ship to Contact)</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>zqu__SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renew Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Subscription</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>zqu__TermStartDate__c</fullName>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/Zuora__Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>Zuora__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora__TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/OpportunityService.cls
public with sharing class OpportunityService {
    // CSP-1306 Nick Wu modified
    // add one more field in the Opportunity query No_of_Times_To_Extend__c
    private static final String OPP_QUERY = 'SELECT '
                                                + 'Id, '
                                                + 'StageName, '
                                                + 'Contract_Signer__c, '
                                                + 'Three_Business_Days_From_Today__c, '
                                                + 'Opportunity_Expiration_Date__c, '
                                                + 'EchoSign_Contract_Due_Date__c, '
                                                + 'No_of_Times_To_Extend__c, '
                                                + 'AccountId, '
                                                + 'Lock_Quotes__c, '
                                                + '(SELECT '
                                                        + 'zqu__TermStartDate__c, '
                                                        + 'zqu__SubscriptionType__c, '
                                                        + 'zqu__BillToContact__c, '
                                                        + 'zqu__SoldToContact__c '
                                                    + 'FROM '
                                                        + 'zqu__Quotes__r '
                                                    + 'ORDER BY '
                                                    + 'CreatedDate DESC ) '
                                            + 'FROM '
                                                + 'Opportunity '
                                            + 'WHERE '
                                                + '{WHERECLAUSE}';


    /**
     * @purpose Validate the Opportunity and Account when user click the cancel reenter button on Opportunity
     * @author  Tony
     * @date    2018-10-31
     * @param   Opportunity Id
     * @return  String errormessage, if no error, return ''
     */
    public static String validateOpportunityQuote(String oppId) {
        String responseErrorMessage = '';

        if(String.isBlank(oppId)) {
            responseErrorMessage = 'Invalid Opportunity ID Provided';
        }

        else{
          String oppQuery = OPP_QUERY.replace('{WHERECLAUSE}', ' Id = :oppId');

          Opportunity currentOpp;

          try{
              currentOpp = Database.query(oppQuery);
              
              List<AccountContactRole> acrList = [Select id from AccountContactRole where AccountId =: currentOpp.AccountId AND (Role = 'Primary' OR Role = 'Billing') LIMIT 1];

              List<Zuora__Subscription__c> subList = [Select Id from Zuora__Subscription__c where Zuora__Account__c =: currentOpp.AccountId AND Zuora__TermEndDate__c >: date.today()];

              if (currentOpp.StageName == 'Closed Won') {
                responseErrorMessage = Label.Opportunity_Closed_Won_Reopen_Error;
              }
              else if (currentOpp.StageName == 'Closed Lost') {
                responseErrorMessage = Label.Opportunity_Closed_Lost_Reopen_Error;
              }
              else if (currentOpp.Lock_Quotes__c) {
                responseErrorMessage = Label.Opportunity_Locked_Warning_Message;
              }
              else if (acrList.isEmpty()) {
                responseErrorMessage = Label.Primary_Account_Contact_Role_Required_Warning_message;
              }
              else if (subList.isEmpty()) {
                responseErrorMessage = Label.Cancel_Reenter_Need_a_Active_Subscription;
              }
              else {
                currentOpp.StageName = 'Quoting';
                update currentOpp;
              }
          } 
          catch(Exception e) {
              responseErrorMessage = e.getMessage();
          }
        }

        return responseErrorMessage;
    }
}