XO_Project_UAT/Project--XOGrp--UAT/src/objects/Quota__c.object
<CustomObject>
    <fields>
        <fullName>Quota__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Quota</label>
        <referenceTo>Quota__c</referenceTo>
        <relationshipLabel>Quotas</relationshipLabel>
        <relationshipName>Child_Quotas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quota</label>
    <nameField>
        <displayFormat>Quota - {000000}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SalesRepID__c</fullName>
        <description>The number Id of the Sales Rep</description>
        <externalId>true</externalId>
        <inlineHelpText>Sales Rep Id from External System</inlineHelpText>
        <label>SalesRep ID</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    public static Quota__c getQuota(Id quotaId) {
        return new Quota__c(
            Quota__c = quotaId
        );
    }

    public static User getUser(String alias, Id managerId, Id profileId) {
    	return new User(
        	FirstName         = 'Test',
        	LastName          = 'User',
        	Alias             = alias,
        	Email             = 'testuser@xogrp.com',
        	Username          = alias + '@asdasfaf.com',
        	TimeZoneSidKey    = 'America/Panama',
        	LocaleSidKey      = 'en_US',
        	EmailEncodingKey  = 'UTF-8',
        	ProfileId         = profileId,
        	LanguageLocaleKey = 'en_US',
        	ManagerId         = managerId,
        	SalesRepId__c     = '12345'
        );
    }
}