XO_Project_UAT/Project--XOGrp--UAT/src/objects/Quota__c.object
<CustomObject>
    <fields>
        <fullName>Indirect_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Indirect Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Quota</label>
        <referenceTo>Quota__c</referenceTo>
        <relationshipLabel>Quotas</relationshipLabel>
        <relationshipName>Child_Quotas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quota</label>
    <nameField>
        <displayFormat>Quota - {000000}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

XO_Project_UAT/Project--XOGrp--UAT/src/classes/QuotaNode.cls
public with sharing class QuotaNode {
    private List<QuotaNode> children;
    private QuotaNode parent;
    public Quota__c record;
    public Boolean visited;

    /**
     * @description node of a tree representing a hierarchy of Quotas
     * with functions enabling easy traversal and summarization of values
    */

    public QuotaNode(Quota__c quota) {
        this.record = quota;
        this.children = new List<QuotaNode>();
        this.visited = false;
    
        //reset the indirect amount to 0, since it will be recalculated
        this.record.Indirect_Amount__c = 0;
    }

    public void addChildQuotaNode(QuotaNode quotaNode) {
        quotaNode.setParent(this);
        this.children.add(quotaNode);
    }

    public List<QuotaNode> getChildren() {
        return this.children;
    }

    public void setParent(QuotaNode quotaNode) {
        this.parent = quotaNode;
    } 

    public QuotaNode getParent() {
        return this.parent;
    }

    /**
     * @description Determine if a node is ready to be summarized, either it has no children
     * or all children have already been visited AND it has not been visited
     *
     * @return Boolean true if it is ready to be summarized false if not
    */
    public Boolean canSummarize() {
        Boolean allChildrenVisited = true;

        Integer index = 0;
        while(!this.visited && allChildrenVisited == true && index < this.children.size()) {
            allChildrenVisited = this.children[index].visited;
            index++;
        }

        return (allChildrenVisited && !this.visited);
    }
}